/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authImport } from './routes/__auth'
import { Route as authIndexImport } from './routes/__auth/index'
import { Route as authMemberImport } from './routes/__auth/member'
import { Route as authAdminImport } from './routes/__auth/admin'
import { Route as authMemberIndexImport } from './routes/__auth/member/index'
import { Route as authAdminIndexImport } from './routes/__auth/admin/index'
import { Route as authMemberNewpolicysetImport } from './routes/__auth/member/new_policy_set'
import { Route as authAdminNewpolicysetImport } from './routes/__auth/admin/new_policy_set'
import { Route as authMemberNewpolicysetStep3Import } from './routes/__auth/member/new_policy_set/step3'
import { Route as authMemberNewpolicysetStep2Import } from './routes/__auth/member/new_policy_set/step2'
import { Route as authMemberNewpolicysetStep1Import } from './routes/__auth/member/new_policy_set/step1'
import { Route as authMemberNewpolicysetAddpolicyImport } from './routes/__auth/member/new_policy_set/add_policy'
import { Route as authAdminNewpolicysetStep3Import } from './routes/__auth/admin/new_policy_set/step3'
import { Route as authAdminNewpolicysetStep2Import } from './routes/__auth/admin/new_policy_set/step2'
import { Route as authAdminNewpolicysetStep1Import } from './routes/__auth/admin/new_policy_set/step1'
import { Route as authAdminNewpolicysetAddpolicyImport } from './routes/__auth/admin/new_policy_set/add_policy'
import { Route as authMemberPolicysetPolicySetIdIndexImport } from './routes/__auth/member/policy_set.$policySetId.index'
import { Route as authAdminPolicysetPolicySetIdIndexImport } from './routes/__auth/admin/policy_set.$policySetId.index'
import { Route as authMemberPolicysetPolicySetIdAddpolicyImport } from './routes/__auth/member/policy_set.$policySetId.add_policy'
import { Route as authMemberNewpolicysetAddpolicyStep3Import } from './routes/__auth/member/new_policy_set/add_policy/step3'
import { Route as authMemberNewpolicysetAddpolicyStep2Import } from './routes/__auth/member/new_policy_set/add_policy/step2'
import { Route as authMemberNewpolicysetAddpolicyStep1Import } from './routes/__auth/member/new_policy_set/add_policy/step1'
import { Route as authAdminPolicysetPolicySetIdAddpolicyImport } from './routes/__auth/admin/policy_set.$policySetId.add_policy'
import { Route as authAdminNewpolicysetAddpolicyStep3Import } from './routes/__auth/admin/new_policy_set/add_policy/step3'
import { Route as authAdminNewpolicysetAddpolicyStep2Import } from './routes/__auth/admin/new_policy_set/add_policy/step2'
import { Route as authAdminNewpolicysetAddpolicyStep1Import } from './routes/__auth/admin/new_policy_set/add_policy/step1'
import { Route as authMemberPolicysetPolicySetIdEditpolicyPolicyIdImport } from './routes/__auth/member/policy_set.$policySetId.edit_policy.$policyId'
import { Route as authMemberPolicysetPolicySetIdAddpolicyStep3Import } from './routes/__auth/member/policy_set.$policySetId.add_policy/step3'
import { Route as authMemberPolicysetPolicySetIdAddpolicyStep2Import } from './routes/__auth/member/policy_set.$policySetId.add_policy/step2'
import { Route as authMemberPolicysetPolicySetIdAddpolicyStep1Import } from './routes/__auth/member/policy_set.$policySetId.add_policy/step1'
import { Route as authAdminPolicysetPolicySetIdEditpolicyPolicyIdImport } from './routes/__auth/admin/policy_set.$policySetId.edit_policy.$policyId'
import { Route as authAdminPolicysetPolicySetIdAddpolicyStep3Import } from './routes/__auth/admin/policy_set.$policySetId.add_policy/step3'
import { Route as authAdminPolicysetPolicySetIdAddpolicyStep2Import } from './routes/__auth/admin/policy_set.$policySetId.add_policy/step2'
import { Route as authAdminPolicysetPolicySetIdAddpolicyStep1Import } from './routes/__auth/admin/policy_set.$policySetId.add_policy/step1'
import { Route as authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep3Import } from './routes/__auth/member/policy_set.$policySetId.edit_policy.$policyId/step3'
import { Route as authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep2Import } from './routes/__auth/member/policy_set.$policySetId.edit_policy.$policyId/step2'
import { Route as authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep1Import } from './routes/__auth/member/policy_set.$policySetId.edit_policy.$policyId/step1'
import { Route as authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep3Import } from './routes/__auth/admin/policy_set.$policySetId.edit_policy.$policyId/step3'
import { Route as authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep2Import } from './routes/__auth/admin/policy_set.$policySetId.edit_policy.$policyId/step2'
import { Route as authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep1Import } from './routes/__auth/admin/policy_set.$policySetId.edit_policy.$policyId/step1'

// Create/Update Routes

const authRoute = authImport.update({
  id: '/__auth',
  getParentRoute: () => rootRoute,
} as any)

const authIndexRoute = authIndexImport.update({
  path: '/',
  getParentRoute: () => authRoute,
} as any)

const authMemberRoute = authMemberImport.update({
  path: '/member',
  getParentRoute: () => authRoute,
} as any)

const authAdminRoute = authAdminImport.update({
  path: '/admin',
  getParentRoute: () => authRoute,
} as any)

const authMemberIndexRoute = authMemberIndexImport.update({
  path: '/',
  getParentRoute: () => authMemberRoute,
} as any)

const authAdminIndexRoute = authAdminIndexImport.update({
  path: '/',
  getParentRoute: () => authAdminRoute,
} as any)

const authMemberNewpolicysetRoute = authMemberNewpolicysetImport.update({
  path: '/new_policy_set',
  getParentRoute: () => authMemberRoute,
} as any)

const authAdminNewpolicysetRoute = authAdminNewpolicysetImport.update({
  path: '/new_policy_set',
  getParentRoute: () => authAdminRoute,
} as any)

const authMemberNewpolicysetStep3Route =
  authMemberNewpolicysetStep3Import.update({
    path: '/step3',
    getParentRoute: () => authMemberNewpolicysetRoute,
  } as any)

const authMemberNewpolicysetStep2Route =
  authMemberNewpolicysetStep2Import.update({
    path: '/step2',
    getParentRoute: () => authMemberNewpolicysetRoute,
  } as any)

const authMemberNewpolicysetStep1Route =
  authMemberNewpolicysetStep1Import.update({
    path: '/step1',
    getParentRoute: () => authMemberNewpolicysetRoute,
  } as any)

const authMemberNewpolicysetAddpolicyRoute =
  authMemberNewpolicysetAddpolicyImport.update({
    path: '/add_policy',
    getParentRoute: () => authMemberNewpolicysetRoute,
  } as any)

const authAdminNewpolicysetStep3Route = authAdminNewpolicysetStep3Import.update(
  {
    path: '/step3',
    getParentRoute: () => authAdminNewpolicysetRoute,
  } as any,
)

const authAdminNewpolicysetStep2Route = authAdminNewpolicysetStep2Import.update(
  {
    path: '/step2',
    getParentRoute: () => authAdminNewpolicysetRoute,
  } as any,
)

const authAdminNewpolicysetStep1Route = authAdminNewpolicysetStep1Import.update(
  {
    path: '/step1',
    getParentRoute: () => authAdminNewpolicysetRoute,
  } as any,
)

const authAdminNewpolicysetAddpolicyRoute =
  authAdminNewpolicysetAddpolicyImport.update({
    path: '/add_policy',
    getParentRoute: () => authAdminNewpolicysetRoute,
  } as any)

const authMemberPolicysetPolicySetIdIndexRoute =
  authMemberPolicysetPolicySetIdIndexImport.update({
    path: '/policy_set/$policySetId/',
    getParentRoute: () => authMemberRoute,
  } as any)

const authAdminPolicysetPolicySetIdIndexRoute =
  authAdminPolicysetPolicySetIdIndexImport.update({
    path: '/policy_set/$policySetId/',
    getParentRoute: () => authAdminRoute,
  } as any)

const authMemberPolicysetPolicySetIdAddpolicyRoute =
  authMemberPolicysetPolicySetIdAddpolicyImport.update({
    path: '/policy_set/$policySetId/add_policy',
    getParentRoute: () => authMemberRoute,
  } as any)

const authMemberNewpolicysetAddpolicyStep3Route =
  authMemberNewpolicysetAddpolicyStep3Import.update({
    path: '/step3',
    getParentRoute: () => authMemberNewpolicysetAddpolicyRoute,
  } as any)

const authMemberNewpolicysetAddpolicyStep2Route =
  authMemberNewpolicysetAddpolicyStep2Import.update({
    path: '/step2',
    getParentRoute: () => authMemberNewpolicysetAddpolicyRoute,
  } as any)

const authMemberNewpolicysetAddpolicyStep1Route =
  authMemberNewpolicysetAddpolicyStep1Import.update({
    path: '/step1',
    getParentRoute: () => authMemberNewpolicysetAddpolicyRoute,
  } as any)

const authAdminPolicysetPolicySetIdAddpolicyRoute =
  authAdminPolicysetPolicySetIdAddpolicyImport.update({
    path: '/policy_set/$policySetId/add_policy',
    getParentRoute: () => authAdminRoute,
  } as any)

const authAdminNewpolicysetAddpolicyStep3Route =
  authAdminNewpolicysetAddpolicyStep3Import.update({
    path: '/step3',
    getParentRoute: () => authAdminNewpolicysetAddpolicyRoute,
  } as any)

const authAdminNewpolicysetAddpolicyStep2Route =
  authAdminNewpolicysetAddpolicyStep2Import.update({
    path: '/step2',
    getParentRoute: () => authAdminNewpolicysetAddpolicyRoute,
  } as any)

const authAdminNewpolicysetAddpolicyStep1Route =
  authAdminNewpolicysetAddpolicyStep1Import.update({
    path: '/step1',
    getParentRoute: () => authAdminNewpolicysetAddpolicyRoute,
  } as any)

const authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute =
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdImport.update({
    path: '/policy_set/$policySetId/edit_policy/$policyId',
    getParentRoute: () => authMemberRoute,
  } as any)

const authMemberPolicysetPolicySetIdAddpolicyStep3Route =
  authMemberPolicysetPolicySetIdAddpolicyStep3Import.update({
    path: '/step3',
    getParentRoute: () => authMemberPolicysetPolicySetIdAddpolicyRoute,
  } as any)

const authMemberPolicysetPolicySetIdAddpolicyStep2Route =
  authMemberPolicysetPolicySetIdAddpolicyStep2Import.update({
    path: '/step2',
    getParentRoute: () => authMemberPolicysetPolicySetIdAddpolicyRoute,
  } as any)

const authMemberPolicysetPolicySetIdAddpolicyStep1Route =
  authMemberPolicysetPolicySetIdAddpolicyStep1Import.update({
    path: '/step1',
    getParentRoute: () => authMemberPolicysetPolicySetIdAddpolicyRoute,
  } as any)

const authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute =
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdImport.update({
    path: '/policy_set/$policySetId/edit_policy/$policyId',
    getParentRoute: () => authAdminRoute,
  } as any)

const authAdminPolicysetPolicySetIdAddpolicyStep3Route =
  authAdminPolicysetPolicySetIdAddpolicyStep3Import.update({
    path: '/step3',
    getParentRoute: () => authAdminPolicysetPolicySetIdAddpolicyRoute,
  } as any)

const authAdminPolicysetPolicySetIdAddpolicyStep2Route =
  authAdminPolicysetPolicySetIdAddpolicyStep2Import.update({
    path: '/step2',
    getParentRoute: () => authAdminPolicysetPolicySetIdAddpolicyRoute,
  } as any)

const authAdminPolicysetPolicySetIdAddpolicyStep1Route =
  authAdminPolicysetPolicySetIdAddpolicyStep1Import.update({
    path: '/step1',
    getParentRoute: () => authAdminPolicysetPolicySetIdAddpolicyRoute,
  } as any)

const authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep3Route =
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep3Import.update({
    path: '/step3',
    getParentRoute: () => authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute,
  } as any)

const authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep2Route =
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep2Import.update({
    path: '/step2',
    getParentRoute: () => authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute,
  } as any)

const authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep1Route =
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep1Import.update({
    path: '/step1',
    getParentRoute: () => authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute,
  } as any)

const authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep3Route =
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep3Import.update({
    path: '/step3',
    getParentRoute: () => authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute,
  } as any)

const authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep2Route =
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep2Import.update({
    path: '/step2',
    getParentRoute: () => authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute,
  } as any)

const authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep1Route =
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep1Import.update({
    path: '/step1',
    getParentRoute: () => authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/__auth/admin': {
      id: '/__auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authAdminImport
      parentRoute: typeof authImport
    }
    '/__auth/member': {
      id: '/__auth/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof authMemberImport
      parentRoute: typeof authImport
    }
    '/__auth/': {
      id: '/__auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexImport
      parentRoute: typeof authImport
    }
    '/__auth/admin/new_policy_set': {
      id: '/__auth/admin/new_policy_set'
      path: '/new_policy_set'
      fullPath: '/admin/new_policy_set'
      preLoaderRoute: typeof authAdminNewpolicysetImport
      parentRoute: typeof authAdminImport
    }
    '/__auth/member/new_policy_set': {
      id: '/__auth/member/new_policy_set'
      path: '/new_policy_set'
      fullPath: '/member/new_policy_set'
      preLoaderRoute: typeof authMemberNewpolicysetImport
      parentRoute: typeof authMemberImport
    }
    '/__auth/admin/': {
      id: '/__auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof authAdminIndexImport
      parentRoute: typeof authAdminImport
    }
    '/__auth/member/': {
      id: '/__auth/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof authMemberIndexImport
      parentRoute: typeof authMemberImport
    }
    '/__auth/admin/new_policy_set/add_policy': {
      id: '/__auth/admin/new_policy_set/add_policy'
      path: '/add_policy'
      fullPath: '/admin/new_policy_set/add_policy'
      preLoaderRoute: typeof authAdminNewpolicysetAddpolicyImport
      parentRoute: typeof authAdminNewpolicysetImport
    }
    '/__auth/admin/new_policy_set/step1': {
      id: '/__auth/admin/new_policy_set/step1'
      path: '/step1'
      fullPath: '/admin/new_policy_set/step1'
      preLoaderRoute: typeof authAdminNewpolicysetStep1Import
      parentRoute: typeof authAdminNewpolicysetImport
    }
    '/__auth/admin/new_policy_set/step2': {
      id: '/__auth/admin/new_policy_set/step2'
      path: '/step2'
      fullPath: '/admin/new_policy_set/step2'
      preLoaderRoute: typeof authAdminNewpolicysetStep2Import
      parentRoute: typeof authAdminNewpolicysetImport
    }
    '/__auth/admin/new_policy_set/step3': {
      id: '/__auth/admin/new_policy_set/step3'
      path: '/step3'
      fullPath: '/admin/new_policy_set/step3'
      preLoaderRoute: typeof authAdminNewpolicysetStep3Import
      parentRoute: typeof authAdminNewpolicysetImport
    }
    '/__auth/member/new_policy_set/add_policy': {
      id: '/__auth/member/new_policy_set/add_policy'
      path: '/add_policy'
      fullPath: '/member/new_policy_set/add_policy'
      preLoaderRoute: typeof authMemberNewpolicysetAddpolicyImport
      parentRoute: typeof authMemberNewpolicysetImport
    }
    '/__auth/member/new_policy_set/step1': {
      id: '/__auth/member/new_policy_set/step1'
      path: '/step1'
      fullPath: '/member/new_policy_set/step1'
      preLoaderRoute: typeof authMemberNewpolicysetStep1Import
      parentRoute: typeof authMemberNewpolicysetImport
    }
    '/__auth/member/new_policy_set/step2': {
      id: '/__auth/member/new_policy_set/step2'
      path: '/step2'
      fullPath: '/member/new_policy_set/step2'
      preLoaderRoute: typeof authMemberNewpolicysetStep2Import
      parentRoute: typeof authMemberNewpolicysetImport
    }
    '/__auth/member/new_policy_set/step3': {
      id: '/__auth/member/new_policy_set/step3'
      path: '/step3'
      fullPath: '/member/new_policy_set/step3'
      preLoaderRoute: typeof authMemberNewpolicysetStep3Import
      parentRoute: typeof authMemberNewpolicysetImport
    }
    '/__auth/admin/new_policy_set/add_policy/step1': {
      id: '/__auth/admin/new_policy_set/add_policy/step1'
      path: '/step1'
      fullPath: '/admin/new_policy_set/add_policy/step1'
      preLoaderRoute: typeof authAdminNewpolicysetAddpolicyStep1Import
      parentRoute: typeof authAdminNewpolicysetAddpolicyImport
    }
    '/__auth/admin/new_policy_set/add_policy/step2': {
      id: '/__auth/admin/new_policy_set/add_policy/step2'
      path: '/step2'
      fullPath: '/admin/new_policy_set/add_policy/step2'
      preLoaderRoute: typeof authAdminNewpolicysetAddpolicyStep2Import
      parentRoute: typeof authAdminNewpolicysetAddpolicyImport
    }
    '/__auth/admin/new_policy_set/add_policy/step3': {
      id: '/__auth/admin/new_policy_set/add_policy/step3'
      path: '/step3'
      fullPath: '/admin/new_policy_set/add_policy/step3'
      preLoaderRoute: typeof authAdminNewpolicysetAddpolicyStep3Import
      parentRoute: typeof authAdminNewpolicysetAddpolicyImport
    }
    '/__auth/admin/policy_set/$policySetId/add_policy': {
      id: '/__auth/admin/policy_set/$policySetId/add_policy'
      path: '/policy_set/$policySetId/add_policy'
      fullPath: '/admin/policy_set/$policySetId/add_policy'
      preLoaderRoute: typeof authAdminPolicysetPolicySetIdAddpolicyImport
      parentRoute: typeof authAdminImport
    }
    '/__auth/member/new_policy_set/add_policy/step1': {
      id: '/__auth/member/new_policy_set/add_policy/step1'
      path: '/step1'
      fullPath: '/member/new_policy_set/add_policy/step1'
      preLoaderRoute: typeof authMemberNewpolicysetAddpolicyStep1Import
      parentRoute: typeof authMemberNewpolicysetAddpolicyImport
    }
    '/__auth/member/new_policy_set/add_policy/step2': {
      id: '/__auth/member/new_policy_set/add_policy/step2'
      path: '/step2'
      fullPath: '/member/new_policy_set/add_policy/step2'
      preLoaderRoute: typeof authMemberNewpolicysetAddpolicyStep2Import
      parentRoute: typeof authMemberNewpolicysetAddpolicyImport
    }
    '/__auth/member/new_policy_set/add_policy/step3': {
      id: '/__auth/member/new_policy_set/add_policy/step3'
      path: '/step3'
      fullPath: '/member/new_policy_set/add_policy/step3'
      preLoaderRoute: typeof authMemberNewpolicysetAddpolicyStep3Import
      parentRoute: typeof authMemberNewpolicysetAddpolicyImport
    }
    '/__auth/member/policy_set/$policySetId/add_policy': {
      id: '/__auth/member/policy_set/$policySetId/add_policy'
      path: '/policy_set/$policySetId/add_policy'
      fullPath: '/member/policy_set/$policySetId/add_policy'
      preLoaderRoute: typeof authMemberPolicysetPolicySetIdAddpolicyImport
      parentRoute: typeof authMemberImport
    }
    '/__auth/admin/policy_set/$policySetId/': {
      id: '/__auth/admin/policy_set/$policySetId/'
      path: '/policy_set/$policySetId'
      fullPath: '/admin/policy_set/$policySetId'
      preLoaderRoute: typeof authAdminPolicysetPolicySetIdIndexImport
      parentRoute: typeof authAdminImport
    }
    '/__auth/member/policy_set/$policySetId/': {
      id: '/__auth/member/policy_set/$policySetId/'
      path: '/policy_set/$policySetId'
      fullPath: '/member/policy_set/$policySetId'
      preLoaderRoute: typeof authMemberPolicysetPolicySetIdIndexImport
      parentRoute: typeof authMemberImport
    }
    '/__auth/admin/policy_set/$policySetId/add_policy/step1': {
      id: '/__auth/admin/policy_set/$policySetId/add_policy/step1'
      path: '/step1'
      fullPath: '/admin/policy_set/$policySetId/add_policy/step1'
      preLoaderRoute: typeof authAdminPolicysetPolicySetIdAddpolicyStep1Import
      parentRoute: typeof authAdminPolicysetPolicySetIdAddpolicyImport
    }
    '/__auth/admin/policy_set/$policySetId/add_policy/step2': {
      id: '/__auth/admin/policy_set/$policySetId/add_policy/step2'
      path: '/step2'
      fullPath: '/admin/policy_set/$policySetId/add_policy/step2'
      preLoaderRoute: typeof authAdminPolicysetPolicySetIdAddpolicyStep2Import
      parentRoute: typeof authAdminPolicysetPolicySetIdAddpolicyImport
    }
    '/__auth/admin/policy_set/$policySetId/add_policy/step3': {
      id: '/__auth/admin/policy_set/$policySetId/add_policy/step3'
      path: '/step3'
      fullPath: '/admin/policy_set/$policySetId/add_policy/step3'
      preLoaderRoute: typeof authAdminPolicysetPolicySetIdAddpolicyStep3Import
      parentRoute: typeof authAdminPolicysetPolicySetIdAddpolicyImport
    }
    '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId': {
      id: '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId'
      path: '/policy_set/$policySetId/edit_policy/$policyId'
      fullPath: '/admin/policy_set/$policySetId/edit_policy/$policyId'
      preLoaderRoute: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdImport
      parentRoute: typeof authAdminImport
    }
    '/__auth/member/policy_set/$policySetId/add_policy/step1': {
      id: '/__auth/member/policy_set/$policySetId/add_policy/step1'
      path: '/step1'
      fullPath: '/member/policy_set/$policySetId/add_policy/step1'
      preLoaderRoute: typeof authMemberPolicysetPolicySetIdAddpolicyStep1Import
      parentRoute: typeof authMemberPolicysetPolicySetIdAddpolicyImport
    }
    '/__auth/member/policy_set/$policySetId/add_policy/step2': {
      id: '/__auth/member/policy_set/$policySetId/add_policy/step2'
      path: '/step2'
      fullPath: '/member/policy_set/$policySetId/add_policy/step2'
      preLoaderRoute: typeof authMemberPolicysetPolicySetIdAddpolicyStep2Import
      parentRoute: typeof authMemberPolicysetPolicySetIdAddpolicyImport
    }
    '/__auth/member/policy_set/$policySetId/add_policy/step3': {
      id: '/__auth/member/policy_set/$policySetId/add_policy/step3'
      path: '/step3'
      fullPath: '/member/policy_set/$policySetId/add_policy/step3'
      preLoaderRoute: typeof authMemberPolicysetPolicySetIdAddpolicyStep3Import
      parentRoute: typeof authMemberPolicysetPolicySetIdAddpolicyImport
    }
    '/__auth/member/policy_set/$policySetId/edit_policy/$policyId': {
      id: '/__auth/member/policy_set/$policySetId/edit_policy/$policyId'
      path: '/policy_set/$policySetId/edit_policy/$policyId'
      fullPath: '/member/policy_set/$policySetId/edit_policy/$policyId'
      preLoaderRoute: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdImport
      parentRoute: typeof authMemberImport
    }
    '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step1': {
      id: '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step1'
      path: '/step1'
      fullPath: '/admin/policy_set/$policySetId/edit_policy/$policyId/step1'
      preLoaderRoute: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep1Import
      parentRoute: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdImport
    }
    '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step2': {
      id: '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step2'
      path: '/step2'
      fullPath: '/admin/policy_set/$policySetId/edit_policy/$policyId/step2'
      preLoaderRoute: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep2Import
      parentRoute: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdImport
    }
    '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step3': {
      id: '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step3'
      path: '/step3'
      fullPath: '/admin/policy_set/$policySetId/edit_policy/$policyId/step3'
      preLoaderRoute: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep3Import
      parentRoute: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdImport
    }
    '/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step1': {
      id: '/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step1'
      path: '/step1'
      fullPath: '/member/policy_set/$policySetId/edit_policy/$policyId/step1'
      preLoaderRoute: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep1Import
      parentRoute: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdImport
    }
    '/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step2': {
      id: '/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step2'
      path: '/step2'
      fullPath: '/member/policy_set/$policySetId/edit_policy/$policyId/step2'
      preLoaderRoute: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep2Import
      parentRoute: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdImport
    }
    '/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step3': {
      id: '/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step3'
      path: '/step3'
      fullPath: '/member/policy_set/$policySetId/edit_policy/$policyId/step3'
      preLoaderRoute: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep3Import
      parentRoute: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdImport
    }
  }
}

// Create and export the route tree

interface authAdminNewpolicysetAddpolicyRouteChildren {
  authAdminNewpolicysetAddpolicyStep1Route: typeof authAdminNewpolicysetAddpolicyStep1Route
  authAdminNewpolicysetAddpolicyStep2Route: typeof authAdminNewpolicysetAddpolicyStep2Route
  authAdminNewpolicysetAddpolicyStep3Route: typeof authAdminNewpolicysetAddpolicyStep3Route
}

const authAdminNewpolicysetAddpolicyRouteChildren: authAdminNewpolicysetAddpolicyRouteChildren =
  {
    authAdminNewpolicysetAddpolicyStep1Route:
      authAdminNewpolicysetAddpolicyStep1Route,
    authAdminNewpolicysetAddpolicyStep2Route:
      authAdminNewpolicysetAddpolicyStep2Route,
    authAdminNewpolicysetAddpolicyStep3Route:
      authAdminNewpolicysetAddpolicyStep3Route,
  }

const authAdminNewpolicysetAddpolicyRouteWithChildren =
  authAdminNewpolicysetAddpolicyRoute._addFileChildren(
    authAdminNewpolicysetAddpolicyRouteChildren,
  )

interface authAdminNewpolicysetRouteChildren {
  authAdminNewpolicysetAddpolicyRoute: typeof authAdminNewpolicysetAddpolicyRouteWithChildren
  authAdminNewpolicysetStep1Route: typeof authAdminNewpolicysetStep1Route
  authAdminNewpolicysetStep2Route: typeof authAdminNewpolicysetStep2Route
  authAdminNewpolicysetStep3Route: typeof authAdminNewpolicysetStep3Route
}

const authAdminNewpolicysetRouteChildren: authAdminNewpolicysetRouteChildren = {
  authAdminNewpolicysetAddpolicyRoute:
    authAdminNewpolicysetAddpolicyRouteWithChildren,
  authAdminNewpolicysetStep1Route: authAdminNewpolicysetStep1Route,
  authAdminNewpolicysetStep2Route: authAdminNewpolicysetStep2Route,
  authAdminNewpolicysetStep3Route: authAdminNewpolicysetStep3Route,
}

const authAdminNewpolicysetRouteWithChildren =
  authAdminNewpolicysetRoute._addFileChildren(
    authAdminNewpolicysetRouteChildren,
  )

interface authAdminPolicysetPolicySetIdAddpolicyRouteChildren {
  authAdminPolicysetPolicySetIdAddpolicyStep1Route: typeof authAdminPolicysetPolicySetIdAddpolicyStep1Route
  authAdminPolicysetPolicySetIdAddpolicyStep2Route: typeof authAdminPolicysetPolicySetIdAddpolicyStep2Route
  authAdminPolicysetPolicySetIdAddpolicyStep3Route: typeof authAdminPolicysetPolicySetIdAddpolicyStep3Route
}

const authAdminPolicysetPolicySetIdAddpolicyRouteChildren: authAdminPolicysetPolicySetIdAddpolicyRouteChildren =
  {
    authAdminPolicysetPolicySetIdAddpolicyStep1Route:
      authAdminPolicysetPolicySetIdAddpolicyStep1Route,
    authAdminPolicysetPolicySetIdAddpolicyStep2Route:
      authAdminPolicysetPolicySetIdAddpolicyStep2Route,
    authAdminPolicysetPolicySetIdAddpolicyStep3Route:
      authAdminPolicysetPolicySetIdAddpolicyStep3Route,
  }

const authAdminPolicysetPolicySetIdAddpolicyRouteWithChildren =
  authAdminPolicysetPolicySetIdAddpolicyRoute._addFileChildren(
    authAdminPolicysetPolicySetIdAddpolicyRouteChildren,
  )

interface authAdminPolicysetPolicySetIdEditpolicyPolicyIdRouteChildren {
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep1Route: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep1Route
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep2Route: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep2Route
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep3Route: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep3Route
}

const authAdminPolicysetPolicySetIdEditpolicyPolicyIdRouteChildren: authAdminPolicysetPolicySetIdEditpolicyPolicyIdRouteChildren =
  {
    authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep1Route:
      authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep1Route,
    authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep2Route:
      authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep2Route,
    authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep3Route:
      authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep3Route,
  }

const authAdminPolicysetPolicySetIdEditpolicyPolicyIdRouteWithChildren =
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute._addFileChildren(
    authAdminPolicysetPolicySetIdEditpolicyPolicyIdRouteChildren,
  )

interface authAdminRouteChildren {
  authAdminNewpolicysetRoute: typeof authAdminNewpolicysetRouteWithChildren
  authAdminIndexRoute: typeof authAdminIndexRoute
  authAdminPolicysetPolicySetIdAddpolicyRoute: typeof authAdminPolicysetPolicySetIdAddpolicyRouteWithChildren
  authAdminPolicysetPolicySetIdIndexRoute: typeof authAdminPolicysetPolicySetIdIndexRoute
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdRouteWithChildren
}

const authAdminRouteChildren: authAdminRouteChildren = {
  authAdminNewpolicysetRoute: authAdminNewpolicysetRouteWithChildren,
  authAdminIndexRoute: authAdminIndexRoute,
  authAdminPolicysetPolicySetIdAddpolicyRoute:
    authAdminPolicysetPolicySetIdAddpolicyRouteWithChildren,
  authAdminPolicysetPolicySetIdIndexRoute:
    authAdminPolicysetPolicySetIdIndexRoute,
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute:
    authAdminPolicysetPolicySetIdEditpolicyPolicyIdRouteWithChildren,
}

const authAdminRouteWithChildren = authAdminRoute._addFileChildren(
  authAdminRouteChildren,
)

interface authMemberNewpolicysetAddpolicyRouteChildren {
  authMemberNewpolicysetAddpolicyStep1Route: typeof authMemberNewpolicysetAddpolicyStep1Route
  authMemberNewpolicysetAddpolicyStep2Route: typeof authMemberNewpolicysetAddpolicyStep2Route
  authMemberNewpolicysetAddpolicyStep3Route: typeof authMemberNewpolicysetAddpolicyStep3Route
}

const authMemberNewpolicysetAddpolicyRouteChildren: authMemberNewpolicysetAddpolicyRouteChildren =
  {
    authMemberNewpolicysetAddpolicyStep1Route:
      authMemberNewpolicysetAddpolicyStep1Route,
    authMemberNewpolicysetAddpolicyStep2Route:
      authMemberNewpolicysetAddpolicyStep2Route,
    authMemberNewpolicysetAddpolicyStep3Route:
      authMemberNewpolicysetAddpolicyStep3Route,
  }

const authMemberNewpolicysetAddpolicyRouteWithChildren =
  authMemberNewpolicysetAddpolicyRoute._addFileChildren(
    authMemberNewpolicysetAddpolicyRouteChildren,
  )

interface authMemberNewpolicysetRouteChildren {
  authMemberNewpolicysetAddpolicyRoute: typeof authMemberNewpolicysetAddpolicyRouteWithChildren
  authMemberNewpolicysetStep1Route: typeof authMemberNewpolicysetStep1Route
  authMemberNewpolicysetStep2Route: typeof authMemberNewpolicysetStep2Route
  authMemberNewpolicysetStep3Route: typeof authMemberNewpolicysetStep3Route
}

const authMemberNewpolicysetRouteChildren: authMemberNewpolicysetRouteChildren =
  {
    authMemberNewpolicysetAddpolicyRoute:
      authMemberNewpolicysetAddpolicyRouteWithChildren,
    authMemberNewpolicysetStep1Route: authMemberNewpolicysetStep1Route,
    authMemberNewpolicysetStep2Route: authMemberNewpolicysetStep2Route,
    authMemberNewpolicysetStep3Route: authMemberNewpolicysetStep3Route,
  }

const authMemberNewpolicysetRouteWithChildren =
  authMemberNewpolicysetRoute._addFileChildren(
    authMemberNewpolicysetRouteChildren,
  )

interface authMemberPolicysetPolicySetIdAddpolicyRouteChildren {
  authMemberPolicysetPolicySetIdAddpolicyStep1Route: typeof authMemberPolicysetPolicySetIdAddpolicyStep1Route
  authMemberPolicysetPolicySetIdAddpolicyStep2Route: typeof authMemberPolicysetPolicySetIdAddpolicyStep2Route
  authMemberPolicysetPolicySetIdAddpolicyStep3Route: typeof authMemberPolicysetPolicySetIdAddpolicyStep3Route
}

const authMemberPolicysetPolicySetIdAddpolicyRouteChildren: authMemberPolicysetPolicySetIdAddpolicyRouteChildren =
  {
    authMemberPolicysetPolicySetIdAddpolicyStep1Route:
      authMemberPolicysetPolicySetIdAddpolicyStep1Route,
    authMemberPolicysetPolicySetIdAddpolicyStep2Route:
      authMemberPolicysetPolicySetIdAddpolicyStep2Route,
    authMemberPolicysetPolicySetIdAddpolicyStep3Route:
      authMemberPolicysetPolicySetIdAddpolicyStep3Route,
  }

const authMemberPolicysetPolicySetIdAddpolicyRouteWithChildren =
  authMemberPolicysetPolicySetIdAddpolicyRoute._addFileChildren(
    authMemberPolicysetPolicySetIdAddpolicyRouteChildren,
  )

interface authMemberPolicysetPolicySetIdEditpolicyPolicyIdRouteChildren {
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep1Route: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep1Route
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep2Route: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep2Route
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep3Route: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep3Route
}

const authMemberPolicysetPolicySetIdEditpolicyPolicyIdRouteChildren: authMemberPolicysetPolicySetIdEditpolicyPolicyIdRouteChildren =
  {
    authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep1Route:
      authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep1Route,
    authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep2Route:
      authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep2Route,
    authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep3Route:
      authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep3Route,
  }

const authMemberPolicysetPolicySetIdEditpolicyPolicyIdRouteWithChildren =
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute._addFileChildren(
    authMemberPolicysetPolicySetIdEditpolicyPolicyIdRouteChildren,
  )

interface authMemberRouteChildren {
  authMemberNewpolicysetRoute: typeof authMemberNewpolicysetRouteWithChildren
  authMemberIndexRoute: typeof authMemberIndexRoute
  authMemberPolicysetPolicySetIdAddpolicyRoute: typeof authMemberPolicysetPolicySetIdAddpolicyRouteWithChildren
  authMemberPolicysetPolicySetIdIndexRoute: typeof authMemberPolicysetPolicySetIdIndexRoute
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdRouteWithChildren
}

const authMemberRouteChildren: authMemberRouteChildren = {
  authMemberNewpolicysetRoute: authMemberNewpolicysetRouteWithChildren,
  authMemberIndexRoute: authMemberIndexRoute,
  authMemberPolicysetPolicySetIdAddpolicyRoute:
    authMemberPolicysetPolicySetIdAddpolicyRouteWithChildren,
  authMemberPolicysetPolicySetIdIndexRoute:
    authMemberPolicysetPolicySetIdIndexRoute,
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute:
    authMemberPolicysetPolicySetIdEditpolicyPolicyIdRouteWithChildren,
}

const authMemberRouteWithChildren = authMemberRoute._addFileChildren(
  authMemberRouteChildren,
)

interface authRouteChildren {
  authAdminRoute: typeof authAdminRouteWithChildren
  authMemberRoute: typeof authMemberRouteWithChildren
  authIndexRoute: typeof authIndexRoute
}

const authRouteChildren: authRouteChildren = {
  authAdminRoute: authAdminRouteWithChildren,
  authMemberRoute: authMemberRouteWithChildren,
  authIndexRoute: authIndexRoute,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof authRouteWithChildren
  '/admin': typeof authAdminRouteWithChildren
  '/member': typeof authMemberRouteWithChildren
  '/': typeof authIndexRoute
  '/admin/new_policy_set': typeof authAdminNewpolicysetRouteWithChildren
  '/member/new_policy_set': typeof authMemberNewpolicysetRouteWithChildren
  '/admin/': typeof authAdminIndexRoute
  '/member/': typeof authMemberIndexRoute
  '/admin/new_policy_set/add_policy': typeof authAdminNewpolicysetAddpolicyRouteWithChildren
  '/admin/new_policy_set/step1': typeof authAdminNewpolicysetStep1Route
  '/admin/new_policy_set/step2': typeof authAdminNewpolicysetStep2Route
  '/admin/new_policy_set/step3': typeof authAdminNewpolicysetStep3Route
  '/member/new_policy_set/add_policy': typeof authMemberNewpolicysetAddpolicyRouteWithChildren
  '/member/new_policy_set/step1': typeof authMemberNewpolicysetStep1Route
  '/member/new_policy_set/step2': typeof authMemberNewpolicysetStep2Route
  '/member/new_policy_set/step3': typeof authMemberNewpolicysetStep3Route
  '/admin/new_policy_set/add_policy/step1': typeof authAdminNewpolicysetAddpolicyStep1Route
  '/admin/new_policy_set/add_policy/step2': typeof authAdminNewpolicysetAddpolicyStep2Route
  '/admin/new_policy_set/add_policy/step3': typeof authAdminNewpolicysetAddpolicyStep3Route
  '/admin/policy_set/$policySetId/add_policy': typeof authAdminPolicysetPolicySetIdAddpolicyRouteWithChildren
  '/member/new_policy_set/add_policy/step1': typeof authMemberNewpolicysetAddpolicyStep1Route
  '/member/new_policy_set/add_policy/step2': typeof authMemberNewpolicysetAddpolicyStep2Route
  '/member/new_policy_set/add_policy/step3': typeof authMemberNewpolicysetAddpolicyStep3Route
  '/member/policy_set/$policySetId/add_policy': typeof authMemberPolicysetPolicySetIdAddpolicyRouteWithChildren
  '/admin/policy_set/$policySetId': typeof authAdminPolicysetPolicySetIdIndexRoute
  '/member/policy_set/$policySetId': typeof authMemberPolicysetPolicySetIdIndexRoute
  '/admin/policy_set/$policySetId/add_policy/step1': typeof authAdminPolicysetPolicySetIdAddpolicyStep1Route
  '/admin/policy_set/$policySetId/add_policy/step2': typeof authAdminPolicysetPolicySetIdAddpolicyStep2Route
  '/admin/policy_set/$policySetId/add_policy/step3': typeof authAdminPolicysetPolicySetIdAddpolicyStep3Route
  '/admin/policy_set/$policySetId/edit_policy/$policyId': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdRouteWithChildren
  '/member/policy_set/$policySetId/add_policy/step1': typeof authMemberPolicysetPolicySetIdAddpolicyStep1Route
  '/member/policy_set/$policySetId/add_policy/step2': typeof authMemberPolicysetPolicySetIdAddpolicyStep2Route
  '/member/policy_set/$policySetId/add_policy/step3': typeof authMemberPolicysetPolicySetIdAddpolicyStep3Route
  '/member/policy_set/$policySetId/edit_policy/$policyId': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdRouteWithChildren
  '/admin/policy_set/$policySetId/edit_policy/$policyId/step1': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep1Route
  '/admin/policy_set/$policySetId/edit_policy/$policyId/step2': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep2Route
  '/admin/policy_set/$policySetId/edit_policy/$policyId/step3': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep3Route
  '/member/policy_set/$policySetId/edit_policy/$policyId/step1': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep1Route
  '/member/policy_set/$policySetId/edit_policy/$policyId/step2': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep2Route
  '/member/policy_set/$policySetId/edit_policy/$policyId/step3': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep3Route
}

export interface FileRoutesByTo {
  '/': typeof authIndexRoute
  '/admin/new_policy_set': typeof authAdminNewpolicysetRouteWithChildren
  '/member/new_policy_set': typeof authMemberNewpolicysetRouteWithChildren
  '/admin': typeof authAdminIndexRoute
  '/member': typeof authMemberIndexRoute
  '/admin/new_policy_set/add_policy': typeof authAdminNewpolicysetAddpolicyRouteWithChildren
  '/admin/new_policy_set/step1': typeof authAdminNewpolicysetStep1Route
  '/admin/new_policy_set/step2': typeof authAdminNewpolicysetStep2Route
  '/admin/new_policy_set/step3': typeof authAdminNewpolicysetStep3Route
  '/member/new_policy_set/add_policy': typeof authMemberNewpolicysetAddpolicyRouteWithChildren
  '/member/new_policy_set/step1': typeof authMemberNewpolicysetStep1Route
  '/member/new_policy_set/step2': typeof authMemberNewpolicysetStep2Route
  '/member/new_policy_set/step3': typeof authMemberNewpolicysetStep3Route
  '/admin/new_policy_set/add_policy/step1': typeof authAdminNewpolicysetAddpolicyStep1Route
  '/admin/new_policy_set/add_policy/step2': typeof authAdminNewpolicysetAddpolicyStep2Route
  '/admin/new_policy_set/add_policy/step3': typeof authAdminNewpolicysetAddpolicyStep3Route
  '/admin/policy_set/$policySetId/add_policy': typeof authAdminPolicysetPolicySetIdAddpolicyRouteWithChildren
  '/member/new_policy_set/add_policy/step1': typeof authMemberNewpolicysetAddpolicyStep1Route
  '/member/new_policy_set/add_policy/step2': typeof authMemberNewpolicysetAddpolicyStep2Route
  '/member/new_policy_set/add_policy/step3': typeof authMemberNewpolicysetAddpolicyStep3Route
  '/member/policy_set/$policySetId/add_policy': typeof authMemberPolicysetPolicySetIdAddpolicyRouteWithChildren
  '/admin/policy_set/$policySetId': typeof authAdminPolicysetPolicySetIdIndexRoute
  '/member/policy_set/$policySetId': typeof authMemberPolicysetPolicySetIdIndexRoute
  '/admin/policy_set/$policySetId/add_policy/step1': typeof authAdminPolicysetPolicySetIdAddpolicyStep1Route
  '/admin/policy_set/$policySetId/add_policy/step2': typeof authAdminPolicysetPolicySetIdAddpolicyStep2Route
  '/admin/policy_set/$policySetId/add_policy/step3': typeof authAdminPolicysetPolicySetIdAddpolicyStep3Route
  '/admin/policy_set/$policySetId/edit_policy/$policyId': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdRouteWithChildren
  '/member/policy_set/$policySetId/add_policy/step1': typeof authMemberPolicysetPolicySetIdAddpolicyStep1Route
  '/member/policy_set/$policySetId/add_policy/step2': typeof authMemberPolicysetPolicySetIdAddpolicyStep2Route
  '/member/policy_set/$policySetId/add_policy/step3': typeof authMemberPolicysetPolicySetIdAddpolicyStep3Route
  '/member/policy_set/$policySetId/edit_policy/$policyId': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdRouteWithChildren
  '/admin/policy_set/$policySetId/edit_policy/$policyId/step1': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep1Route
  '/admin/policy_set/$policySetId/edit_policy/$policyId/step2': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep2Route
  '/admin/policy_set/$policySetId/edit_policy/$policyId/step3': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep3Route
  '/member/policy_set/$policySetId/edit_policy/$policyId/step1': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep1Route
  '/member/policy_set/$policySetId/edit_policy/$policyId/step2': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep2Route
  '/member/policy_set/$policySetId/edit_policy/$policyId/step3': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep3Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/__auth': typeof authRouteWithChildren
  '/__auth/admin': typeof authAdminRouteWithChildren
  '/__auth/member': typeof authMemberRouteWithChildren
  '/__auth/': typeof authIndexRoute
  '/__auth/admin/new_policy_set': typeof authAdminNewpolicysetRouteWithChildren
  '/__auth/member/new_policy_set': typeof authMemberNewpolicysetRouteWithChildren
  '/__auth/admin/': typeof authAdminIndexRoute
  '/__auth/member/': typeof authMemberIndexRoute
  '/__auth/admin/new_policy_set/add_policy': typeof authAdminNewpolicysetAddpolicyRouteWithChildren
  '/__auth/admin/new_policy_set/step1': typeof authAdminNewpolicysetStep1Route
  '/__auth/admin/new_policy_set/step2': typeof authAdminNewpolicysetStep2Route
  '/__auth/admin/new_policy_set/step3': typeof authAdminNewpolicysetStep3Route
  '/__auth/member/new_policy_set/add_policy': typeof authMemberNewpolicysetAddpolicyRouteWithChildren
  '/__auth/member/new_policy_set/step1': typeof authMemberNewpolicysetStep1Route
  '/__auth/member/new_policy_set/step2': typeof authMemberNewpolicysetStep2Route
  '/__auth/member/new_policy_set/step3': typeof authMemberNewpolicysetStep3Route
  '/__auth/admin/new_policy_set/add_policy/step1': typeof authAdminNewpolicysetAddpolicyStep1Route
  '/__auth/admin/new_policy_set/add_policy/step2': typeof authAdminNewpolicysetAddpolicyStep2Route
  '/__auth/admin/new_policy_set/add_policy/step3': typeof authAdminNewpolicysetAddpolicyStep3Route
  '/__auth/admin/policy_set/$policySetId/add_policy': typeof authAdminPolicysetPolicySetIdAddpolicyRouteWithChildren
  '/__auth/member/new_policy_set/add_policy/step1': typeof authMemberNewpolicysetAddpolicyStep1Route
  '/__auth/member/new_policy_set/add_policy/step2': typeof authMemberNewpolicysetAddpolicyStep2Route
  '/__auth/member/new_policy_set/add_policy/step3': typeof authMemberNewpolicysetAddpolicyStep3Route
  '/__auth/member/policy_set/$policySetId/add_policy': typeof authMemberPolicysetPolicySetIdAddpolicyRouteWithChildren
  '/__auth/admin/policy_set/$policySetId/': typeof authAdminPolicysetPolicySetIdIndexRoute
  '/__auth/member/policy_set/$policySetId/': typeof authMemberPolicysetPolicySetIdIndexRoute
  '/__auth/admin/policy_set/$policySetId/add_policy/step1': typeof authAdminPolicysetPolicySetIdAddpolicyStep1Route
  '/__auth/admin/policy_set/$policySetId/add_policy/step2': typeof authAdminPolicysetPolicySetIdAddpolicyStep2Route
  '/__auth/admin/policy_set/$policySetId/add_policy/step3': typeof authAdminPolicysetPolicySetIdAddpolicyStep3Route
  '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdRouteWithChildren
  '/__auth/member/policy_set/$policySetId/add_policy/step1': typeof authMemberPolicysetPolicySetIdAddpolicyStep1Route
  '/__auth/member/policy_set/$policySetId/add_policy/step2': typeof authMemberPolicysetPolicySetIdAddpolicyStep2Route
  '/__auth/member/policy_set/$policySetId/add_policy/step3': typeof authMemberPolicysetPolicySetIdAddpolicyStep3Route
  '/__auth/member/policy_set/$policySetId/edit_policy/$policyId': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdRouteWithChildren
  '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step1': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep1Route
  '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step2': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep2Route
  '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step3': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdStep3Route
  '/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step1': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep1Route
  '/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step2': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep2Route
  '/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step3': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdStep3Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/admin'
    | '/member'
    | '/'
    | '/admin/new_policy_set'
    | '/member/new_policy_set'
    | '/admin/'
    | '/member/'
    | '/admin/new_policy_set/add_policy'
    | '/admin/new_policy_set/step1'
    | '/admin/new_policy_set/step2'
    | '/admin/new_policy_set/step3'
    | '/member/new_policy_set/add_policy'
    | '/member/new_policy_set/step1'
    | '/member/new_policy_set/step2'
    | '/member/new_policy_set/step3'
    | '/admin/new_policy_set/add_policy/step1'
    | '/admin/new_policy_set/add_policy/step2'
    | '/admin/new_policy_set/add_policy/step3'
    | '/admin/policy_set/$policySetId/add_policy'
    | '/member/new_policy_set/add_policy/step1'
    | '/member/new_policy_set/add_policy/step2'
    | '/member/new_policy_set/add_policy/step3'
    | '/member/policy_set/$policySetId/add_policy'
    | '/admin/policy_set/$policySetId'
    | '/member/policy_set/$policySetId'
    | '/admin/policy_set/$policySetId/add_policy/step1'
    | '/admin/policy_set/$policySetId/add_policy/step2'
    | '/admin/policy_set/$policySetId/add_policy/step3'
    | '/admin/policy_set/$policySetId/edit_policy/$policyId'
    | '/member/policy_set/$policySetId/add_policy/step1'
    | '/member/policy_set/$policySetId/add_policy/step2'
    | '/member/policy_set/$policySetId/add_policy/step3'
    | '/member/policy_set/$policySetId/edit_policy/$policyId'
    | '/admin/policy_set/$policySetId/edit_policy/$policyId/step1'
    | '/admin/policy_set/$policySetId/edit_policy/$policyId/step2'
    | '/admin/policy_set/$policySetId/edit_policy/$policyId/step3'
    | '/member/policy_set/$policySetId/edit_policy/$policyId/step1'
    | '/member/policy_set/$policySetId/edit_policy/$policyId/step2'
    | '/member/policy_set/$policySetId/edit_policy/$policyId/step3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/new_policy_set'
    | '/member/new_policy_set'
    | '/admin'
    | '/member'
    | '/admin/new_policy_set/add_policy'
    | '/admin/new_policy_set/step1'
    | '/admin/new_policy_set/step2'
    | '/admin/new_policy_set/step3'
    | '/member/new_policy_set/add_policy'
    | '/member/new_policy_set/step1'
    | '/member/new_policy_set/step2'
    | '/member/new_policy_set/step3'
    | '/admin/new_policy_set/add_policy/step1'
    | '/admin/new_policy_set/add_policy/step2'
    | '/admin/new_policy_set/add_policy/step3'
    | '/admin/policy_set/$policySetId/add_policy'
    | '/member/new_policy_set/add_policy/step1'
    | '/member/new_policy_set/add_policy/step2'
    | '/member/new_policy_set/add_policy/step3'
    | '/member/policy_set/$policySetId/add_policy'
    | '/admin/policy_set/$policySetId'
    | '/member/policy_set/$policySetId'
    | '/admin/policy_set/$policySetId/add_policy/step1'
    | '/admin/policy_set/$policySetId/add_policy/step2'
    | '/admin/policy_set/$policySetId/add_policy/step3'
    | '/admin/policy_set/$policySetId/edit_policy/$policyId'
    | '/member/policy_set/$policySetId/add_policy/step1'
    | '/member/policy_set/$policySetId/add_policy/step2'
    | '/member/policy_set/$policySetId/add_policy/step3'
    | '/member/policy_set/$policySetId/edit_policy/$policyId'
    | '/admin/policy_set/$policySetId/edit_policy/$policyId/step1'
    | '/admin/policy_set/$policySetId/edit_policy/$policyId/step2'
    | '/admin/policy_set/$policySetId/edit_policy/$policyId/step3'
    | '/member/policy_set/$policySetId/edit_policy/$policyId/step1'
    | '/member/policy_set/$policySetId/edit_policy/$policyId/step2'
    | '/member/policy_set/$policySetId/edit_policy/$policyId/step3'
  id:
    | '__root__'
    | '/__auth'
    | '/__auth/admin'
    | '/__auth/member'
    | '/__auth/'
    | '/__auth/admin/new_policy_set'
    | '/__auth/member/new_policy_set'
    | '/__auth/admin/'
    | '/__auth/member/'
    | '/__auth/admin/new_policy_set/add_policy'
    | '/__auth/admin/new_policy_set/step1'
    | '/__auth/admin/new_policy_set/step2'
    | '/__auth/admin/new_policy_set/step3'
    | '/__auth/member/new_policy_set/add_policy'
    | '/__auth/member/new_policy_set/step1'
    | '/__auth/member/new_policy_set/step2'
    | '/__auth/member/new_policy_set/step3'
    | '/__auth/admin/new_policy_set/add_policy/step1'
    | '/__auth/admin/new_policy_set/add_policy/step2'
    | '/__auth/admin/new_policy_set/add_policy/step3'
    | '/__auth/admin/policy_set/$policySetId/add_policy'
    | '/__auth/member/new_policy_set/add_policy/step1'
    | '/__auth/member/new_policy_set/add_policy/step2'
    | '/__auth/member/new_policy_set/add_policy/step3'
    | '/__auth/member/policy_set/$policySetId/add_policy'
    | '/__auth/admin/policy_set/$policySetId/'
    | '/__auth/member/policy_set/$policySetId/'
    | '/__auth/admin/policy_set/$policySetId/add_policy/step1'
    | '/__auth/admin/policy_set/$policySetId/add_policy/step2'
    | '/__auth/admin/policy_set/$policySetId/add_policy/step3'
    | '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId'
    | '/__auth/member/policy_set/$policySetId/add_policy/step1'
    | '/__auth/member/policy_set/$policySetId/add_policy/step2'
    | '/__auth/member/policy_set/$policySetId/add_policy/step3'
    | '/__auth/member/policy_set/$policySetId/edit_policy/$policyId'
    | '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step1'
    | '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step2'
    | '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step3'
    | '/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step1'
    | '/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step2'
    | '/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step3'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRoute: typeof authRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  authRoute: authRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/__auth"
      ]
    },
    "/__auth": {
      "filePath": "__auth.tsx",
      "children": [
        "/__auth/admin",
        "/__auth/member",
        "/__auth/"
      ]
    },
    "/__auth/admin": {
      "filePath": "__auth/admin.tsx",
      "parent": "/__auth",
      "children": [
        "/__auth/admin/new_policy_set",
        "/__auth/admin/",
        "/__auth/admin/policy_set/$policySetId/add_policy",
        "/__auth/admin/policy_set/$policySetId/",
        "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId"
      ]
    },
    "/__auth/member": {
      "filePath": "__auth/member.tsx",
      "parent": "/__auth",
      "children": [
        "/__auth/member/new_policy_set",
        "/__auth/member/",
        "/__auth/member/policy_set/$policySetId/add_policy",
        "/__auth/member/policy_set/$policySetId/",
        "/__auth/member/policy_set/$policySetId/edit_policy/$policyId"
      ]
    },
    "/__auth/": {
      "filePath": "__auth/index.tsx",
      "parent": "/__auth"
    },
    "/__auth/admin/new_policy_set": {
      "filePath": "__auth/admin/new_policy_set.tsx",
      "parent": "/__auth/admin",
      "children": [
        "/__auth/admin/new_policy_set/add_policy",
        "/__auth/admin/new_policy_set/step1",
        "/__auth/admin/new_policy_set/step2",
        "/__auth/admin/new_policy_set/step3"
      ]
    },
    "/__auth/member/new_policy_set": {
      "filePath": "__auth/member/new_policy_set.tsx",
      "parent": "/__auth/member",
      "children": [
        "/__auth/member/new_policy_set/add_policy",
        "/__auth/member/new_policy_set/step1",
        "/__auth/member/new_policy_set/step2",
        "/__auth/member/new_policy_set/step3"
      ]
    },
    "/__auth/admin/": {
      "filePath": "__auth/admin/index.tsx",
      "parent": "/__auth/admin"
    },
    "/__auth/member/": {
      "filePath": "__auth/member/index.tsx",
      "parent": "/__auth/member"
    },
    "/__auth/admin/new_policy_set/add_policy": {
      "filePath": "__auth/admin/new_policy_set/add_policy.tsx",
      "parent": "/__auth/admin/new_policy_set",
      "children": [
        "/__auth/admin/new_policy_set/add_policy/step1",
        "/__auth/admin/new_policy_set/add_policy/step2",
        "/__auth/admin/new_policy_set/add_policy/step3"
      ]
    },
    "/__auth/admin/new_policy_set/step1": {
      "filePath": "__auth/admin/new_policy_set/step1.tsx",
      "parent": "/__auth/admin/new_policy_set"
    },
    "/__auth/admin/new_policy_set/step2": {
      "filePath": "__auth/admin/new_policy_set/step2.tsx",
      "parent": "/__auth/admin/new_policy_set"
    },
    "/__auth/admin/new_policy_set/step3": {
      "filePath": "__auth/admin/new_policy_set/step3.tsx",
      "parent": "/__auth/admin/new_policy_set"
    },
    "/__auth/member/new_policy_set/add_policy": {
      "filePath": "__auth/member/new_policy_set/add_policy.tsx",
      "parent": "/__auth/member/new_policy_set",
      "children": [
        "/__auth/member/new_policy_set/add_policy/step1",
        "/__auth/member/new_policy_set/add_policy/step2",
        "/__auth/member/new_policy_set/add_policy/step3"
      ]
    },
    "/__auth/member/new_policy_set/step1": {
      "filePath": "__auth/member/new_policy_set/step1.tsx",
      "parent": "/__auth/member/new_policy_set"
    },
    "/__auth/member/new_policy_set/step2": {
      "filePath": "__auth/member/new_policy_set/step2.tsx",
      "parent": "/__auth/member/new_policy_set"
    },
    "/__auth/member/new_policy_set/step3": {
      "filePath": "__auth/member/new_policy_set/step3.tsx",
      "parent": "/__auth/member/new_policy_set"
    },
    "/__auth/admin/new_policy_set/add_policy/step1": {
      "filePath": "__auth/admin/new_policy_set/add_policy/step1.tsx",
      "parent": "/__auth/admin/new_policy_set/add_policy"
    },
    "/__auth/admin/new_policy_set/add_policy/step2": {
      "filePath": "__auth/admin/new_policy_set/add_policy/step2.tsx",
      "parent": "/__auth/admin/new_policy_set/add_policy"
    },
    "/__auth/admin/new_policy_set/add_policy/step3": {
      "filePath": "__auth/admin/new_policy_set/add_policy/step3.tsx",
      "parent": "/__auth/admin/new_policy_set/add_policy"
    },
    "/__auth/admin/policy_set/$policySetId/add_policy": {
      "filePath": "__auth/admin/policy_set.$policySetId.add_policy.tsx",
      "parent": "/__auth/admin",
      "children": [
        "/__auth/admin/policy_set/$policySetId/add_policy/step1",
        "/__auth/admin/policy_set/$policySetId/add_policy/step2",
        "/__auth/admin/policy_set/$policySetId/add_policy/step3"
      ]
    },
    "/__auth/member/new_policy_set/add_policy/step1": {
      "filePath": "__auth/member/new_policy_set/add_policy/step1.tsx",
      "parent": "/__auth/member/new_policy_set/add_policy"
    },
    "/__auth/member/new_policy_set/add_policy/step2": {
      "filePath": "__auth/member/new_policy_set/add_policy/step2.tsx",
      "parent": "/__auth/member/new_policy_set/add_policy"
    },
    "/__auth/member/new_policy_set/add_policy/step3": {
      "filePath": "__auth/member/new_policy_set/add_policy/step3.tsx",
      "parent": "/__auth/member/new_policy_set/add_policy"
    },
    "/__auth/member/policy_set/$policySetId/add_policy": {
      "filePath": "__auth/member/policy_set.$policySetId.add_policy.tsx",
      "parent": "/__auth/member",
      "children": [
        "/__auth/member/policy_set/$policySetId/add_policy/step1",
        "/__auth/member/policy_set/$policySetId/add_policy/step2",
        "/__auth/member/policy_set/$policySetId/add_policy/step3"
      ]
    },
    "/__auth/admin/policy_set/$policySetId/": {
      "filePath": "__auth/admin/policy_set.$policySetId.index.tsx",
      "parent": "/__auth/admin"
    },
    "/__auth/member/policy_set/$policySetId/": {
      "filePath": "__auth/member/policy_set.$policySetId.index.tsx",
      "parent": "/__auth/member"
    },
    "/__auth/admin/policy_set/$policySetId/add_policy/step1": {
      "filePath": "__auth/admin/policy_set.$policySetId.add_policy/step1.tsx",
      "parent": "/__auth/admin/policy_set/$policySetId/add_policy"
    },
    "/__auth/admin/policy_set/$policySetId/add_policy/step2": {
      "filePath": "__auth/admin/policy_set.$policySetId.add_policy/step2.tsx",
      "parent": "/__auth/admin/policy_set/$policySetId/add_policy"
    },
    "/__auth/admin/policy_set/$policySetId/add_policy/step3": {
      "filePath": "__auth/admin/policy_set.$policySetId.add_policy/step3.tsx",
      "parent": "/__auth/admin/policy_set/$policySetId/add_policy"
    },
    "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId": {
      "filePath": "__auth/admin/policy_set.$policySetId.edit_policy.$policyId.tsx",
      "parent": "/__auth/admin",
      "children": [
        "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step1",
        "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step2",
        "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step3"
      ]
    },
    "/__auth/member/policy_set/$policySetId/add_policy/step1": {
      "filePath": "__auth/member/policy_set.$policySetId.add_policy/step1.tsx",
      "parent": "/__auth/member/policy_set/$policySetId/add_policy"
    },
    "/__auth/member/policy_set/$policySetId/add_policy/step2": {
      "filePath": "__auth/member/policy_set.$policySetId.add_policy/step2.tsx",
      "parent": "/__auth/member/policy_set/$policySetId/add_policy"
    },
    "/__auth/member/policy_set/$policySetId/add_policy/step3": {
      "filePath": "__auth/member/policy_set.$policySetId.add_policy/step3.tsx",
      "parent": "/__auth/member/policy_set/$policySetId/add_policy"
    },
    "/__auth/member/policy_set/$policySetId/edit_policy/$policyId": {
      "filePath": "__auth/member/policy_set.$policySetId.edit_policy.$policyId.tsx",
      "parent": "/__auth/member",
      "children": [
        "/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step1",
        "/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step2",
        "/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step3"
      ]
    },
    "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step1": {
      "filePath": "__auth/admin/policy_set.$policySetId.edit_policy.$policyId/step1.tsx",
      "parent": "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId"
    },
    "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step2": {
      "filePath": "__auth/admin/policy_set.$policySetId.edit_policy.$policyId/step2.tsx",
      "parent": "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId"
    },
    "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId/step3": {
      "filePath": "__auth/admin/policy_set.$policySetId.edit_policy.$policyId/step3.tsx",
      "parent": "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId"
    },
    "/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step1": {
      "filePath": "__auth/member/policy_set.$policySetId.edit_policy.$policyId/step1.tsx",
      "parent": "/__auth/member/policy_set/$policySetId/edit_policy/$policyId"
    },
    "/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step2": {
      "filePath": "__auth/member/policy_set.$policySetId.edit_policy.$policyId/step2.tsx",
      "parent": "/__auth/member/policy_set/$policySetId/edit_policy/$policyId"
    },
    "/__auth/member/policy_set/$policySetId/edit_policy/$policyId/step3": {
      "filePath": "__auth/member/policy_set.$policySetId.edit_policy.$policyId/step3.tsx",
      "parent": "/__auth/member/policy_set/$policySetId/edit_policy/$policyId"
    }
  }
}
ROUTE_MANIFEST_END */
