/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CallbackImport } from './routes/callback'
import { Route as authImport } from './routes/__auth'
import { Route as authIndexImport } from './routes/__auth/index'
import { Route as authMemberImport } from './routes/__auth/member'
import { Route as authAdminImport } from './routes/__auth/admin'
import { Route as authMemberNewpolicysetImport } from './routes/__auth/member/new_policy_set'
import { Route as authAdminPolicysettemplatesImport } from './routes/__auth/admin/policy_set_templates'
import { Route as authAdminPolicysetImport } from './routes/__auth/admin/policy_set'
import { Route as authAdminNewpolicysetImport } from './routes/__auth/admin/new_policy_set'
import { Route as authMemberNewpolicysetReviewandsubmitImport } from './routes/__auth/member/new_policy_set/review_and_submit'
import { Route as authMemberNewpolicysetPrefilltemplateImport } from './routes/__auth/member/new_policy_set/prefill_template'
import { Route as authMemberNewpolicysetDefinepolicysetImport } from './routes/__auth/member/new_policy_set/define_policy_set'
import { Route as authMemberNewpolicysetAddpoliciesImport } from './routes/__auth/member/new_policy_set/add_policies'
import { Route as authAdminPolicysettemplatesNewpolicysettemplateImport } from './routes/__auth/admin/policy_set_templates.new_policy_set_template'
import { Route as authAdminNewpolicysetReviewandsubmitImport } from './routes/__auth/admin/new_policy_set/review_and_submit'
import { Route as authAdminNewpolicysetPrefilltemplateImport } from './routes/__auth/admin/new_policy_set/prefill_template'
import { Route as authAdminNewpolicysetDefinepolicysetImport } from './routes/__auth/admin/new_policy_set/define_policy_set'
import { Route as authAdminNewpolicysetAddpoliciesImport } from './routes/__auth/admin/new_policy_set/add_policies'
import { Route as authMemberPolicysetPolicySetIdIndexImport } from './routes/__auth/member/policy_set.$policySetId.index'
import { Route as authAdminPolicysetPolicySetIdIndexImport } from './routes/__auth/admin/policy_set.$policySetId.index'
import { Route as authMemberPolicysetPolicySetIdAddpolicyImport } from './routes/__auth/member/policy_set.$policySetId.add_policy'
import { Route as authAdminPolicysettemplatesNewpolicysettemplateReviewandsubmitImport } from './routes/__auth/admin/policy_set_templates.new_policy_set_template/review_and_submit'
import { Route as authAdminPolicysettemplatesNewpolicysettemplateDefinepolicysettemplateImport } from './routes/__auth/admin/policy_set_templates.new_policy_set_template/define_policy_set_template'
import { Route as authAdminPolicysettemplatesNewpolicysettemplateAddpoliciesImport } from './routes/__auth/admin/policy_set_templates.new_policy_set_template/add_policies'
import { Route as authAdminPolicysettemplatesDetailPolicySetTemplateIdImport } from './routes/__auth/admin/policy_set_templates.detail.$policySetTemplateId'
import { Route as authAdminPolicysetPolicySetIdAddpolicyImport } from './routes/__auth/admin/policy_set.$policySetId.add_policy'
import { Route as authMemberPolicysetPolicySetIdEditpolicyPolicyIdImport } from './routes/__auth/member/policy_set.$policySetId.edit_policy.$policyId'
import { Route as authAdminPolicysetPolicySetIdEditpolicyPolicyIdImport } from './routes/__auth/admin/policy_set.$policySetId.edit_policy.$policyId'

// Create/Update Routes

const CallbackRoute = CallbackImport.update({
  path: '/callback',
  getParentRoute: () => rootRoute,
} as any)

const authRoute = authImport.update({
  id: '/__auth',
  getParentRoute: () => rootRoute,
} as any)

const authIndexRoute = authIndexImport.update({
  path: '/',
  getParentRoute: () => authRoute,
} as any)

const authMemberRoute = authMemberImport.update({
  path: '/member',
  getParentRoute: () => authRoute,
} as any)

const authAdminRoute = authAdminImport.update({
  path: '/admin',
  getParentRoute: () => authRoute,
} as any)

const authMemberNewpolicysetRoute = authMemberNewpolicysetImport.update({
  path: '/new_policy_set',
  getParentRoute: () => authMemberRoute,
} as any)

const authAdminPolicysettemplatesRoute =
  authAdminPolicysettemplatesImport.update({
    path: '/policy_set_templates',
    getParentRoute: () => authAdminRoute,
  } as any)

const authAdminPolicysetRoute = authAdminPolicysetImport.update({
  path: '/policy_set',
  getParentRoute: () => authAdminRoute,
} as any)

const authAdminNewpolicysetRoute = authAdminNewpolicysetImport.update({
  path: '/new_policy_set',
  getParentRoute: () => authAdminRoute,
} as any)

const authMemberNewpolicysetReviewandsubmitRoute =
  authMemberNewpolicysetReviewandsubmitImport.update({
    path: '/review_and_submit',
    getParentRoute: () => authMemberNewpolicysetRoute,
  } as any)

const authMemberNewpolicysetPrefilltemplateRoute =
  authMemberNewpolicysetPrefilltemplateImport.update({
    path: '/prefill_template',
    getParentRoute: () => authMemberNewpolicysetRoute,
  } as any)

const authMemberNewpolicysetDefinepolicysetRoute =
  authMemberNewpolicysetDefinepolicysetImport.update({
    path: '/define_policy_set',
    getParentRoute: () => authMemberNewpolicysetRoute,
  } as any)

const authMemberNewpolicysetAddpoliciesRoute =
  authMemberNewpolicysetAddpoliciesImport.update({
    path: '/add_policies',
    getParentRoute: () => authMemberNewpolicysetRoute,
  } as any)

const authAdminPolicysettemplatesNewpolicysettemplateRoute =
  authAdminPolicysettemplatesNewpolicysettemplateImport.update({
    path: '/new_policy_set_template',
    getParentRoute: () => authAdminPolicysettemplatesRoute,
  } as any)

const authAdminNewpolicysetReviewandsubmitRoute =
  authAdminNewpolicysetReviewandsubmitImport.update({
    path: '/review_and_submit',
    getParentRoute: () => authAdminNewpolicysetRoute,
  } as any)

const authAdminNewpolicysetPrefilltemplateRoute =
  authAdminNewpolicysetPrefilltemplateImport.update({
    path: '/prefill_template',
    getParentRoute: () => authAdminNewpolicysetRoute,
  } as any)

const authAdminNewpolicysetDefinepolicysetRoute =
  authAdminNewpolicysetDefinepolicysetImport.update({
    path: '/define_policy_set',
    getParentRoute: () => authAdminNewpolicysetRoute,
  } as any)

const authAdminNewpolicysetAddpoliciesRoute =
  authAdminNewpolicysetAddpoliciesImport.update({
    path: '/add_policies',
    getParentRoute: () => authAdminNewpolicysetRoute,
  } as any)

const authMemberPolicysetPolicySetIdIndexRoute =
  authMemberPolicysetPolicySetIdIndexImport.update({
    path: '/policy_set/$policySetId/',
    getParentRoute: () => authMemberRoute,
  } as any)

const authAdminPolicysetPolicySetIdIndexRoute =
  authAdminPolicysetPolicySetIdIndexImport.update({
    path: '/$policySetId/',
    getParentRoute: () => authAdminPolicysetRoute,
  } as any)

const authMemberPolicysetPolicySetIdAddpolicyRoute =
  authMemberPolicysetPolicySetIdAddpolicyImport.update({
    path: '/policy_set/$policySetId/add_policy',
    getParentRoute: () => authMemberRoute,
  } as any)

const authAdminPolicysettemplatesNewpolicysettemplateReviewandsubmitRoute =
  authAdminPolicysettemplatesNewpolicysettemplateReviewandsubmitImport.update({
    path: '/review_and_submit',
    getParentRoute: () => authAdminPolicysettemplatesNewpolicysettemplateRoute,
  } as any)

const authAdminPolicysettemplatesNewpolicysettemplateDefinepolicysettemplateRoute =
  authAdminPolicysettemplatesNewpolicysettemplateDefinepolicysettemplateImport.update(
    {
      path: '/define_policy_set_template',
      getParentRoute: () =>
        authAdminPolicysettemplatesNewpolicysettemplateRoute,
    } as any,
  )

const authAdminPolicysettemplatesNewpolicysettemplateAddpoliciesRoute =
  authAdminPolicysettemplatesNewpolicysettemplateAddpoliciesImport.update({
    path: '/add_policies',
    getParentRoute: () => authAdminPolicysettemplatesNewpolicysettemplateRoute,
  } as any)

const authAdminPolicysettemplatesDetailPolicySetTemplateIdRoute =
  authAdminPolicysettemplatesDetailPolicySetTemplateIdImport.update({
    path: '/detail/$policySetTemplateId',
    getParentRoute: () => authAdminPolicysettemplatesRoute,
  } as any)

const authAdminPolicysetPolicySetIdAddpolicyRoute =
  authAdminPolicysetPolicySetIdAddpolicyImport.update({
    path: '/$policySetId/add_policy',
    getParentRoute: () => authAdminPolicysetRoute,
  } as any)

const authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute =
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdImport.update({
    path: '/policy_set/$policySetId/edit_policy/$policyId',
    getParentRoute: () => authMemberRoute,
  } as any)

const authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute =
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdImport.update({
    path: '/$policySetId/edit_policy/$policyId',
    getParentRoute: () => authAdminPolicysetRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackImport
      parentRoute: typeof rootRoute
    }
    '/__auth/admin': {
      id: '/__auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof authAdminImport
      parentRoute: typeof authImport
    }
    '/__auth/member': {
      id: '/__auth/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof authMemberImport
      parentRoute: typeof authImport
    }
    '/__auth/': {
      id: '/__auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexImport
      parentRoute: typeof authImport
    }
    '/__auth/admin/new_policy_set': {
      id: '/__auth/admin/new_policy_set'
      path: '/new_policy_set'
      fullPath: '/admin/new_policy_set'
      preLoaderRoute: typeof authAdminNewpolicysetImport
      parentRoute: typeof authAdminImport
    }
    '/__auth/admin/policy_set': {
      id: '/__auth/admin/policy_set'
      path: '/policy_set'
      fullPath: '/admin/policy_set'
      preLoaderRoute: typeof authAdminPolicysetImport
      parentRoute: typeof authAdminImport
    }
    '/__auth/admin/policy_set_templates': {
      id: '/__auth/admin/policy_set_templates'
      path: '/policy_set_templates'
      fullPath: '/admin/policy_set_templates'
      preLoaderRoute: typeof authAdminPolicysettemplatesImport
      parentRoute: typeof authAdminImport
    }
    '/__auth/member/new_policy_set': {
      id: '/__auth/member/new_policy_set'
      path: '/new_policy_set'
      fullPath: '/member/new_policy_set'
      preLoaderRoute: typeof authMemberNewpolicysetImport
      parentRoute: typeof authMemberImport
    }
    '/__auth/admin/new_policy_set/add_policies': {
      id: '/__auth/admin/new_policy_set/add_policies'
      path: '/add_policies'
      fullPath: '/admin/new_policy_set/add_policies'
      preLoaderRoute: typeof authAdminNewpolicysetAddpoliciesImport
      parentRoute: typeof authAdminNewpolicysetImport
    }
    '/__auth/admin/new_policy_set/define_policy_set': {
      id: '/__auth/admin/new_policy_set/define_policy_set'
      path: '/define_policy_set'
      fullPath: '/admin/new_policy_set/define_policy_set'
      preLoaderRoute: typeof authAdminNewpolicysetDefinepolicysetImport
      parentRoute: typeof authAdminNewpolicysetImport
    }
    '/__auth/admin/new_policy_set/prefill_template': {
      id: '/__auth/admin/new_policy_set/prefill_template'
      path: '/prefill_template'
      fullPath: '/admin/new_policy_set/prefill_template'
      preLoaderRoute: typeof authAdminNewpolicysetPrefilltemplateImport
      parentRoute: typeof authAdminNewpolicysetImport
    }
    '/__auth/admin/new_policy_set/review_and_submit': {
      id: '/__auth/admin/new_policy_set/review_and_submit'
      path: '/review_and_submit'
      fullPath: '/admin/new_policy_set/review_and_submit'
      preLoaderRoute: typeof authAdminNewpolicysetReviewandsubmitImport
      parentRoute: typeof authAdminNewpolicysetImport
    }
    '/__auth/admin/policy_set_templates/new_policy_set_template': {
      id: '/__auth/admin/policy_set_templates/new_policy_set_template'
      path: '/new_policy_set_template'
      fullPath: '/admin/policy_set_templates/new_policy_set_template'
      preLoaderRoute: typeof authAdminPolicysettemplatesNewpolicysettemplateImport
      parentRoute: typeof authAdminPolicysettemplatesImport
    }
    '/__auth/member/new_policy_set/add_policies': {
      id: '/__auth/member/new_policy_set/add_policies'
      path: '/add_policies'
      fullPath: '/member/new_policy_set/add_policies'
      preLoaderRoute: typeof authMemberNewpolicysetAddpoliciesImport
      parentRoute: typeof authMemberNewpolicysetImport
    }
    '/__auth/member/new_policy_set/define_policy_set': {
      id: '/__auth/member/new_policy_set/define_policy_set'
      path: '/define_policy_set'
      fullPath: '/member/new_policy_set/define_policy_set'
      preLoaderRoute: typeof authMemberNewpolicysetDefinepolicysetImport
      parentRoute: typeof authMemberNewpolicysetImport
    }
    '/__auth/member/new_policy_set/prefill_template': {
      id: '/__auth/member/new_policy_set/prefill_template'
      path: '/prefill_template'
      fullPath: '/member/new_policy_set/prefill_template'
      preLoaderRoute: typeof authMemberNewpolicysetPrefilltemplateImport
      parentRoute: typeof authMemberNewpolicysetImport
    }
    '/__auth/member/new_policy_set/review_and_submit': {
      id: '/__auth/member/new_policy_set/review_and_submit'
      path: '/review_and_submit'
      fullPath: '/member/new_policy_set/review_and_submit'
      preLoaderRoute: typeof authMemberNewpolicysetReviewandsubmitImport
      parentRoute: typeof authMemberNewpolicysetImport
    }
    '/__auth/admin/policy_set/$policySetId/add_policy': {
      id: '/__auth/admin/policy_set/$policySetId/add_policy'
      path: '/$policySetId/add_policy'
      fullPath: '/admin/policy_set/$policySetId/add_policy'
      preLoaderRoute: typeof authAdminPolicysetPolicySetIdAddpolicyImport
      parentRoute: typeof authAdminPolicysetImport
    }
    '/__auth/admin/policy_set_templates/detail/$policySetTemplateId': {
      id: '/__auth/admin/policy_set_templates/detail/$policySetTemplateId'
      path: '/detail/$policySetTemplateId'
      fullPath: '/admin/policy_set_templates/detail/$policySetTemplateId'
      preLoaderRoute: typeof authAdminPolicysettemplatesDetailPolicySetTemplateIdImport
      parentRoute: typeof authAdminPolicysettemplatesImport
    }
    '/__auth/admin/policy_set_templates/new_policy_set_template/add_policies': {
      id: '/__auth/admin/policy_set_templates/new_policy_set_template/add_policies'
      path: '/add_policies'
      fullPath: '/admin/policy_set_templates/new_policy_set_template/add_policies'
      preLoaderRoute: typeof authAdminPolicysettemplatesNewpolicysettemplateAddpoliciesImport
      parentRoute: typeof authAdminPolicysettemplatesNewpolicysettemplateImport
    }
    '/__auth/admin/policy_set_templates/new_policy_set_template/define_policy_set_template': {
      id: '/__auth/admin/policy_set_templates/new_policy_set_template/define_policy_set_template'
      path: '/define_policy_set_template'
      fullPath: '/admin/policy_set_templates/new_policy_set_template/define_policy_set_template'
      preLoaderRoute: typeof authAdminPolicysettemplatesNewpolicysettemplateDefinepolicysettemplateImport
      parentRoute: typeof authAdminPolicysettemplatesNewpolicysettemplateImport
    }
    '/__auth/admin/policy_set_templates/new_policy_set_template/review_and_submit': {
      id: '/__auth/admin/policy_set_templates/new_policy_set_template/review_and_submit'
      path: '/review_and_submit'
      fullPath: '/admin/policy_set_templates/new_policy_set_template/review_and_submit'
      preLoaderRoute: typeof authAdminPolicysettemplatesNewpolicysettemplateReviewandsubmitImport
      parentRoute: typeof authAdminPolicysettemplatesNewpolicysettemplateImport
    }
    '/__auth/member/policy_set/$policySetId/add_policy': {
      id: '/__auth/member/policy_set/$policySetId/add_policy'
      path: '/policy_set/$policySetId/add_policy'
      fullPath: '/member/policy_set/$policySetId/add_policy'
      preLoaderRoute: typeof authMemberPolicysetPolicySetIdAddpolicyImport
      parentRoute: typeof authMemberImport
    }
    '/__auth/admin/policy_set/$policySetId/': {
      id: '/__auth/admin/policy_set/$policySetId/'
      path: '/$policySetId'
      fullPath: '/admin/policy_set/$policySetId'
      preLoaderRoute: typeof authAdminPolicysetPolicySetIdIndexImport
      parentRoute: typeof authAdminPolicysetImport
    }
    '/__auth/member/policy_set/$policySetId/': {
      id: '/__auth/member/policy_set/$policySetId/'
      path: '/policy_set/$policySetId'
      fullPath: '/member/policy_set/$policySetId'
      preLoaderRoute: typeof authMemberPolicysetPolicySetIdIndexImport
      parentRoute: typeof authMemberImport
    }
    '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId': {
      id: '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId'
      path: '/$policySetId/edit_policy/$policyId'
      fullPath: '/admin/policy_set/$policySetId/edit_policy/$policyId'
      preLoaderRoute: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdImport
      parentRoute: typeof authAdminPolicysetImport
    }
    '/__auth/member/policy_set/$policySetId/edit_policy/$policyId': {
      id: '/__auth/member/policy_set/$policySetId/edit_policy/$policyId'
      path: '/policy_set/$policySetId/edit_policy/$policyId'
      fullPath: '/member/policy_set/$policySetId/edit_policy/$policyId'
      preLoaderRoute: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdImport
      parentRoute: typeof authMemberImport
    }
  }
}

// Create and export the route tree

interface authAdminNewpolicysetRouteChildren {
  authAdminNewpolicysetAddpoliciesRoute: typeof authAdminNewpolicysetAddpoliciesRoute
  authAdminNewpolicysetDefinepolicysetRoute: typeof authAdminNewpolicysetDefinepolicysetRoute
  authAdminNewpolicysetPrefilltemplateRoute: typeof authAdminNewpolicysetPrefilltemplateRoute
  authAdminNewpolicysetReviewandsubmitRoute: typeof authAdminNewpolicysetReviewandsubmitRoute
}

const authAdminNewpolicysetRouteChildren: authAdminNewpolicysetRouteChildren = {
  authAdminNewpolicysetAddpoliciesRoute: authAdminNewpolicysetAddpoliciesRoute,
  authAdminNewpolicysetDefinepolicysetRoute:
    authAdminNewpolicysetDefinepolicysetRoute,
  authAdminNewpolicysetPrefilltemplateRoute:
    authAdminNewpolicysetPrefilltemplateRoute,
  authAdminNewpolicysetReviewandsubmitRoute:
    authAdminNewpolicysetReviewandsubmitRoute,
}

const authAdminNewpolicysetRouteWithChildren =
  authAdminNewpolicysetRoute._addFileChildren(
    authAdminNewpolicysetRouteChildren,
  )

interface authAdminPolicysetRouteChildren {
  authAdminPolicysetPolicySetIdAddpolicyRoute: typeof authAdminPolicysetPolicySetIdAddpolicyRoute
  authAdminPolicysetPolicySetIdIndexRoute: typeof authAdminPolicysetPolicySetIdIndexRoute
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute: typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute
}

const authAdminPolicysetRouteChildren: authAdminPolicysetRouteChildren = {
  authAdminPolicysetPolicySetIdAddpolicyRoute:
    authAdminPolicysetPolicySetIdAddpolicyRoute,
  authAdminPolicysetPolicySetIdIndexRoute:
    authAdminPolicysetPolicySetIdIndexRoute,
  authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute:
    authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute,
}

const authAdminPolicysetRouteWithChildren =
  authAdminPolicysetRoute._addFileChildren(authAdminPolicysetRouteChildren)

interface authAdminPolicysettemplatesNewpolicysettemplateRouteChildren {
  authAdminPolicysettemplatesNewpolicysettemplateAddpoliciesRoute: typeof authAdminPolicysettemplatesNewpolicysettemplateAddpoliciesRoute
  authAdminPolicysettemplatesNewpolicysettemplateDefinepolicysettemplateRoute: typeof authAdminPolicysettemplatesNewpolicysettemplateDefinepolicysettemplateRoute
  authAdminPolicysettemplatesNewpolicysettemplateReviewandsubmitRoute: typeof authAdminPolicysettemplatesNewpolicysettemplateReviewandsubmitRoute
}

const authAdminPolicysettemplatesNewpolicysettemplateRouteChildren: authAdminPolicysettemplatesNewpolicysettemplateRouteChildren =
  {
    authAdminPolicysettemplatesNewpolicysettemplateAddpoliciesRoute:
      authAdminPolicysettemplatesNewpolicysettemplateAddpoliciesRoute,
    authAdminPolicysettemplatesNewpolicysettemplateDefinepolicysettemplateRoute:
      authAdminPolicysettemplatesNewpolicysettemplateDefinepolicysettemplateRoute,
    authAdminPolicysettemplatesNewpolicysettemplateReviewandsubmitRoute:
      authAdminPolicysettemplatesNewpolicysettemplateReviewandsubmitRoute,
  }

const authAdminPolicysettemplatesNewpolicysettemplateRouteWithChildren =
  authAdminPolicysettemplatesNewpolicysettemplateRoute._addFileChildren(
    authAdminPolicysettemplatesNewpolicysettemplateRouteChildren,
  )

interface authAdminPolicysettemplatesRouteChildren {
  authAdminPolicysettemplatesNewpolicysettemplateRoute: typeof authAdminPolicysettemplatesNewpolicysettemplateRouteWithChildren
  authAdminPolicysettemplatesDetailPolicySetTemplateIdRoute: typeof authAdminPolicysettemplatesDetailPolicySetTemplateIdRoute
}

const authAdminPolicysettemplatesRouteChildren: authAdminPolicysettemplatesRouteChildren =
  {
    authAdminPolicysettemplatesNewpolicysettemplateRoute:
      authAdminPolicysettemplatesNewpolicysettemplateRouteWithChildren,
    authAdminPolicysettemplatesDetailPolicySetTemplateIdRoute:
      authAdminPolicysettemplatesDetailPolicySetTemplateIdRoute,
  }

const authAdminPolicysettemplatesRouteWithChildren =
  authAdminPolicysettemplatesRoute._addFileChildren(
    authAdminPolicysettemplatesRouteChildren,
  )

interface authAdminRouteChildren {
  authAdminNewpolicysetRoute: typeof authAdminNewpolicysetRouteWithChildren
  authAdminPolicysetRoute: typeof authAdminPolicysetRouteWithChildren
  authAdminPolicysettemplatesRoute: typeof authAdminPolicysettemplatesRouteWithChildren
}

const authAdminRouteChildren: authAdminRouteChildren = {
  authAdminNewpolicysetRoute: authAdminNewpolicysetRouteWithChildren,
  authAdminPolicysetRoute: authAdminPolicysetRouteWithChildren,
  authAdminPolicysettemplatesRoute:
    authAdminPolicysettemplatesRouteWithChildren,
}

const authAdminRouteWithChildren = authAdminRoute._addFileChildren(
  authAdminRouteChildren,
)

interface authMemberNewpolicysetRouteChildren {
  authMemberNewpolicysetAddpoliciesRoute: typeof authMemberNewpolicysetAddpoliciesRoute
  authMemberNewpolicysetDefinepolicysetRoute: typeof authMemberNewpolicysetDefinepolicysetRoute
  authMemberNewpolicysetPrefilltemplateRoute: typeof authMemberNewpolicysetPrefilltemplateRoute
  authMemberNewpolicysetReviewandsubmitRoute: typeof authMemberNewpolicysetReviewandsubmitRoute
}

const authMemberNewpolicysetRouteChildren: authMemberNewpolicysetRouteChildren =
  {
    authMemberNewpolicysetAddpoliciesRoute:
      authMemberNewpolicysetAddpoliciesRoute,
    authMemberNewpolicysetDefinepolicysetRoute:
      authMemberNewpolicysetDefinepolicysetRoute,
    authMemberNewpolicysetPrefilltemplateRoute:
      authMemberNewpolicysetPrefilltemplateRoute,
    authMemberNewpolicysetReviewandsubmitRoute:
      authMemberNewpolicysetReviewandsubmitRoute,
  }

const authMemberNewpolicysetRouteWithChildren =
  authMemberNewpolicysetRoute._addFileChildren(
    authMemberNewpolicysetRouteChildren,
  )

interface authMemberRouteChildren {
  authMemberNewpolicysetRoute: typeof authMemberNewpolicysetRouteWithChildren
  authMemberPolicysetPolicySetIdAddpolicyRoute: typeof authMemberPolicysetPolicySetIdAddpolicyRoute
  authMemberPolicysetPolicySetIdIndexRoute: typeof authMemberPolicysetPolicySetIdIndexRoute
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute: typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute
}

const authMemberRouteChildren: authMemberRouteChildren = {
  authMemberNewpolicysetRoute: authMemberNewpolicysetRouteWithChildren,
  authMemberPolicysetPolicySetIdAddpolicyRoute:
    authMemberPolicysetPolicySetIdAddpolicyRoute,
  authMemberPolicysetPolicySetIdIndexRoute:
    authMemberPolicysetPolicySetIdIndexRoute,
  authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute:
    authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute,
}

const authMemberRouteWithChildren = authMemberRoute._addFileChildren(
  authMemberRouteChildren,
)

interface authRouteChildren {
  authAdminRoute: typeof authAdminRouteWithChildren
  authMemberRoute: typeof authMemberRouteWithChildren
  authIndexRoute: typeof authIndexRoute
}

const authRouteChildren: authRouteChildren = {
  authAdminRoute: authAdminRouteWithChildren,
  authMemberRoute: authMemberRouteWithChildren,
  authIndexRoute: authIndexRoute,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof authRouteWithChildren
  '/callback': typeof CallbackRoute
  '/admin': typeof authAdminRouteWithChildren
  '/member': typeof authMemberRouteWithChildren
  '/': typeof authIndexRoute
  '/admin/new_policy_set': typeof authAdminNewpolicysetRouteWithChildren
  '/admin/policy_set': typeof authAdminPolicysetRouteWithChildren
  '/admin/policy_set_templates': typeof authAdminPolicysettemplatesRouteWithChildren
  '/member/new_policy_set': typeof authMemberNewpolicysetRouteWithChildren
  '/admin/new_policy_set/add_policies': typeof authAdminNewpolicysetAddpoliciesRoute
  '/admin/new_policy_set/define_policy_set': typeof authAdminNewpolicysetDefinepolicysetRoute
  '/admin/new_policy_set/prefill_template': typeof authAdminNewpolicysetPrefilltemplateRoute
  '/admin/new_policy_set/review_and_submit': typeof authAdminNewpolicysetReviewandsubmitRoute
  '/admin/policy_set_templates/new_policy_set_template': typeof authAdminPolicysettemplatesNewpolicysettemplateRouteWithChildren
  '/member/new_policy_set/add_policies': typeof authMemberNewpolicysetAddpoliciesRoute
  '/member/new_policy_set/define_policy_set': typeof authMemberNewpolicysetDefinepolicysetRoute
  '/member/new_policy_set/prefill_template': typeof authMemberNewpolicysetPrefilltemplateRoute
  '/member/new_policy_set/review_and_submit': typeof authMemberNewpolicysetReviewandsubmitRoute
  '/admin/policy_set/$policySetId/add_policy': typeof authAdminPolicysetPolicySetIdAddpolicyRoute
  '/admin/policy_set_templates/detail/$policySetTemplateId': typeof authAdminPolicysettemplatesDetailPolicySetTemplateIdRoute
  '/admin/policy_set_templates/new_policy_set_template/add_policies': typeof authAdminPolicysettemplatesNewpolicysettemplateAddpoliciesRoute
  '/admin/policy_set_templates/new_policy_set_template/define_policy_set_template': typeof authAdminPolicysettemplatesNewpolicysettemplateDefinepolicysettemplateRoute
  '/admin/policy_set_templates/new_policy_set_template/review_and_submit': typeof authAdminPolicysettemplatesNewpolicysettemplateReviewandsubmitRoute
  '/member/policy_set/$policySetId/add_policy': typeof authMemberPolicysetPolicySetIdAddpolicyRoute
  '/admin/policy_set/$policySetId': typeof authAdminPolicysetPolicySetIdIndexRoute
  '/member/policy_set/$policySetId': typeof authMemberPolicysetPolicySetIdIndexRoute
  '/admin/policy_set/$policySetId/edit_policy/$policyId': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute
  '/member/policy_set/$policySetId/edit_policy/$policyId': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute
}

export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/admin': typeof authAdminRouteWithChildren
  '/member': typeof authMemberRouteWithChildren
  '/': typeof authIndexRoute
  '/admin/new_policy_set': typeof authAdminNewpolicysetRouteWithChildren
  '/admin/policy_set': typeof authAdminPolicysetRouteWithChildren
  '/admin/policy_set_templates': typeof authAdminPolicysettemplatesRouteWithChildren
  '/member/new_policy_set': typeof authMemberNewpolicysetRouteWithChildren
  '/admin/new_policy_set/add_policies': typeof authAdminNewpolicysetAddpoliciesRoute
  '/admin/new_policy_set/define_policy_set': typeof authAdminNewpolicysetDefinepolicysetRoute
  '/admin/new_policy_set/prefill_template': typeof authAdminNewpolicysetPrefilltemplateRoute
  '/admin/new_policy_set/review_and_submit': typeof authAdminNewpolicysetReviewandsubmitRoute
  '/admin/policy_set_templates/new_policy_set_template': typeof authAdminPolicysettemplatesNewpolicysettemplateRouteWithChildren
  '/member/new_policy_set/add_policies': typeof authMemberNewpolicysetAddpoliciesRoute
  '/member/new_policy_set/define_policy_set': typeof authMemberNewpolicysetDefinepolicysetRoute
  '/member/new_policy_set/prefill_template': typeof authMemberNewpolicysetPrefilltemplateRoute
  '/member/new_policy_set/review_and_submit': typeof authMemberNewpolicysetReviewandsubmitRoute
  '/admin/policy_set/$policySetId/add_policy': typeof authAdminPolicysetPolicySetIdAddpolicyRoute
  '/admin/policy_set_templates/detail/$policySetTemplateId': typeof authAdminPolicysettemplatesDetailPolicySetTemplateIdRoute
  '/admin/policy_set_templates/new_policy_set_template/add_policies': typeof authAdminPolicysettemplatesNewpolicysettemplateAddpoliciesRoute
  '/admin/policy_set_templates/new_policy_set_template/define_policy_set_template': typeof authAdminPolicysettemplatesNewpolicysettemplateDefinepolicysettemplateRoute
  '/admin/policy_set_templates/new_policy_set_template/review_and_submit': typeof authAdminPolicysettemplatesNewpolicysettemplateReviewandsubmitRoute
  '/member/policy_set/$policySetId/add_policy': typeof authMemberPolicysetPolicySetIdAddpolicyRoute
  '/admin/policy_set/$policySetId': typeof authAdminPolicysetPolicySetIdIndexRoute
  '/member/policy_set/$policySetId': typeof authMemberPolicysetPolicySetIdIndexRoute
  '/admin/policy_set/$policySetId/edit_policy/$policyId': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute
  '/member/policy_set/$policySetId/edit_policy/$policyId': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/__auth': typeof authRouteWithChildren
  '/callback': typeof CallbackRoute
  '/__auth/admin': typeof authAdminRouteWithChildren
  '/__auth/member': typeof authMemberRouteWithChildren
  '/__auth/': typeof authIndexRoute
  '/__auth/admin/new_policy_set': typeof authAdminNewpolicysetRouteWithChildren
  '/__auth/admin/policy_set': typeof authAdminPolicysetRouteWithChildren
  '/__auth/admin/policy_set_templates': typeof authAdminPolicysettemplatesRouteWithChildren
  '/__auth/member/new_policy_set': typeof authMemberNewpolicysetRouteWithChildren
  '/__auth/admin/new_policy_set/add_policies': typeof authAdminNewpolicysetAddpoliciesRoute
  '/__auth/admin/new_policy_set/define_policy_set': typeof authAdminNewpolicysetDefinepolicysetRoute
  '/__auth/admin/new_policy_set/prefill_template': typeof authAdminNewpolicysetPrefilltemplateRoute
  '/__auth/admin/new_policy_set/review_and_submit': typeof authAdminNewpolicysetReviewandsubmitRoute
  '/__auth/admin/policy_set_templates/new_policy_set_template': typeof authAdminPolicysettemplatesNewpolicysettemplateRouteWithChildren
  '/__auth/member/new_policy_set/add_policies': typeof authMemberNewpolicysetAddpoliciesRoute
  '/__auth/member/new_policy_set/define_policy_set': typeof authMemberNewpolicysetDefinepolicysetRoute
  '/__auth/member/new_policy_set/prefill_template': typeof authMemberNewpolicysetPrefilltemplateRoute
  '/__auth/member/new_policy_set/review_and_submit': typeof authMemberNewpolicysetReviewandsubmitRoute
  '/__auth/admin/policy_set/$policySetId/add_policy': typeof authAdminPolicysetPolicySetIdAddpolicyRoute
  '/__auth/admin/policy_set_templates/detail/$policySetTemplateId': typeof authAdminPolicysettemplatesDetailPolicySetTemplateIdRoute
  '/__auth/admin/policy_set_templates/new_policy_set_template/add_policies': typeof authAdminPolicysettemplatesNewpolicysettemplateAddpoliciesRoute
  '/__auth/admin/policy_set_templates/new_policy_set_template/define_policy_set_template': typeof authAdminPolicysettemplatesNewpolicysettemplateDefinepolicysettemplateRoute
  '/__auth/admin/policy_set_templates/new_policy_set_template/review_and_submit': typeof authAdminPolicysettemplatesNewpolicysettemplateReviewandsubmitRoute
  '/__auth/member/policy_set/$policySetId/add_policy': typeof authMemberPolicysetPolicySetIdAddpolicyRoute
  '/__auth/admin/policy_set/$policySetId/': typeof authAdminPolicysetPolicySetIdIndexRoute
  '/__auth/member/policy_set/$policySetId/': typeof authMemberPolicysetPolicySetIdIndexRoute
  '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId': typeof authAdminPolicysetPolicySetIdEditpolicyPolicyIdRoute
  '/__auth/member/policy_set/$policySetId/edit_policy/$policyId': typeof authMemberPolicysetPolicySetIdEditpolicyPolicyIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/callback'
    | '/admin'
    | '/member'
    | '/'
    | '/admin/new_policy_set'
    | '/admin/policy_set'
    | '/admin/policy_set_templates'
    | '/member/new_policy_set'
    | '/admin/new_policy_set/add_policies'
    | '/admin/new_policy_set/define_policy_set'
    | '/admin/new_policy_set/prefill_template'
    | '/admin/new_policy_set/review_and_submit'
    | '/admin/policy_set_templates/new_policy_set_template'
    | '/member/new_policy_set/add_policies'
    | '/member/new_policy_set/define_policy_set'
    | '/member/new_policy_set/prefill_template'
    | '/member/new_policy_set/review_and_submit'
    | '/admin/policy_set/$policySetId/add_policy'
    | '/admin/policy_set_templates/detail/$policySetTemplateId'
    | '/admin/policy_set_templates/new_policy_set_template/add_policies'
    | '/admin/policy_set_templates/new_policy_set_template/define_policy_set_template'
    | '/admin/policy_set_templates/new_policy_set_template/review_and_submit'
    | '/member/policy_set/$policySetId/add_policy'
    | '/admin/policy_set/$policySetId'
    | '/member/policy_set/$policySetId'
    | '/admin/policy_set/$policySetId/edit_policy/$policyId'
    | '/member/policy_set/$policySetId/edit_policy/$policyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/admin'
    | '/member'
    | '/'
    | '/admin/new_policy_set'
    | '/admin/policy_set'
    | '/admin/policy_set_templates'
    | '/member/new_policy_set'
    | '/admin/new_policy_set/add_policies'
    | '/admin/new_policy_set/define_policy_set'
    | '/admin/new_policy_set/prefill_template'
    | '/admin/new_policy_set/review_and_submit'
    | '/admin/policy_set_templates/new_policy_set_template'
    | '/member/new_policy_set/add_policies'
    | '/member/new_policy_set/define_policy_set'
    | '/member/new_policy_set/prefill_template'
    | '/member/new_policy_set/review_and_submit'
    | '/admin/policy_set/$policySetId/add_policy'
    | '/admin/policy_set_templates/detail/$policySetTemplateId'
    | '/admin/policy_set_templates/new_policy_set_template/add_policies'
    | '/admin/policy_set_templates/new_policy_set_template/define_policy_set_template'
    | '/admin/policy_set_templates/new_policy_set_template/review_and_submit'
    | '/member/policy_set/$policySetId/add_policy'
    | '/admin/policy_set/$policySetId'
    | '/member/policy_set/$policySetId'
    | '/admin/policy_set/$policySetId/edit_policy/$policyId'
    | '/member/policy_set/$policySetId/edit_policy/$policyId'
  id:
    | '__root__'
    | '/__auth'
    | '/callback'
    | '/__auth/admin'
    | '/__auth/member'
    | '/__auth/'
    | '/__auth/admin/new_policy_set'
    | '/__auth/admin/policy_set'
    | '/__auth/admin/policy_set_templates'
    | '/__auth/member/new_policy_set'
    | '/__auth/admin/new_policy_set/add_policies'
    | '/__auth/admin/new_policy_set/define_policy_set'
    | '/__auth/admin/new_policy_set/prefill_template'
    | '/__auth/admin/new_policy_set/review_and_submit'
    | '/__auth/admin/policy_set_templates/new_policy_set_template'
    | '/__auth/member/new_policy_set/add_policies'
    | '/__auth/member/new_policy_set/define_policy_set'
    | '/__auth/member/new_policy_set/prefill_template'
    | '/__auth/member/new_policy_set/review_and_submit'
    | '/__auth/admin/policy_set/$policySetId/add_policy'
    | '/__auth/admin/policy_set_templates/detail/$policySetTemplateId'
    | '/__auth/admin/policy_set_templates/new_policy_set_template/add_policies'
    | '/__auth/admin/policy_set_templates/new_policy_set_template/define_policy_set_template'
    | '/__auth/admin/policy_set_templates/new_policy_set_template/review_and_submit'
    | '/__auth/member/policy_set/$policySetId/add_policy'
    | '/__auth/admin/policy_set/$policySetId/'
    | '/__auth/member/policy_set/$policySetId/'
    | '/__auth/admin/policy_set/$policySetId/edit_policy/$policyId'
    | '/__auth/member/policy_set/$policySetId/edit_policy/$policyId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authRoute: typeof authRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  authRoute: authRouteWithChildren,
  CallbackRoute: CallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/__auth",
        "/callback"
      ]
    },
    "/__auth": {
      "filePath": "__auth.tsx",
      "children": [
        "/__auth/admin",
        "/__auth/member",
        "/__auth/"
      ]
    },
    "/callback": {
      "filePath": "callback.tsx"
    },
    "/__auth/admin": {
      "filePath": "__auth/admin.tsx",
      "parent": "/__auth",
      "children": [
        "/__auth/admin/new_policy_set",
        "/__auth/admin/policy_set",
        "/__auth/admin/policy_set_templates"
      ]
    },
    "/__auth/member": {
      "filePath": "__auth/member.tsx",
      "parent": "/__auth",
      "children": [
        "/__auth/member/new_policy_set",
        "/__auth/member/policy_set/$policySetId/add_policy",
        "/__auth/member/policy_set/$policySetId/",
        "/__auth/member/policy_set/$policySetId/edit_policy/$policyId"
      ]
    },
    "/__auth/": {
      "filePath": "__auth/index.tsx",
      "parent": "/__auth"
    },
    "/__auth/admin/new_policy_set": {
      "filePath": "__auth/admin/new_policy_set.tsx",
      "parent": "/__auth/admin",
      "children": [
        "/__auth/admin/new_policy_set/add_policies",
        "/__auth/admin/new_policy_set/define_policy_set",
        "/__auth/admin/new_policy_set/prefill_template",
        "/__auth/admin/new_policy_set/review_and_submit"
      ]
    },
    "/__auth/admin/policy_set": {
      "filePath": "__auth/admin/policy_set.tsx",
      "parent": "/__auth/admin",
      "children": [
        "/__auth/admin/policy_set/$policySetId/add_policy",
        "/__auth/admin/policy_set/$policySetId/",
        "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId"
      ]
    },
    "/__auth/admin/policy_set_templates": {
      "filePath": "__auth/admin/policy_set_templates.tsx",
      "parent": "/__auth/admin",
      "children": [
        "/__auth/admin/policy_set_templates/new_policy_set_template",
        "/__auth/admin/policy_set_templates/detail/$policySetTemplateId"
      ]
    },
    "/__auth/member/new_policy_set": {
      "filePath": "__auth/member/new_policy_set.tsx",
      "parent": "/__auth/member",
      "children": [
        "/__auth/member/new_policy_set/add_policies",
        "/__auth/member/new_policy_set/define_policy_set",
        "/__auth/member/new_policy_set/prefill_template",
        "/__auth/member/new_policy_set/review_and_submit"
      ]
    },
    "/__auth/admin/new_policy_set/add_policies": {
      "filePath": "__auth/admin/new_policy_set/add_policies.tsx",
      "parent": "/__auth/admin/new_policy_set"
    },
    "/__auth/admin/new_policy_set/define_policy_set": {
      "filePath": "__auth/admin/new_policy_set/define_policy_set.tsx",
      "parent": "/__auth/admin/new_policy_set"
    },
    "/__auth/admin/new_policy_set/prefill_template": {
      "filePath": "__auth/admin/new_policy_set/prefill_template.tsx",
      "parent": "/__auth/admin/new_policy_set"
    },
    "/__auth/admin/new_policy_set/review_and_submit": {
      "filePath": "__auth/admin/new_policy_set/review_and_submit.tsx",
      "parent": "/__auth/admin/new_policy_set"
    },
    "/__auth/admin/policy_set_templates/new_policy_set_template": {
      "filePath": "__auth/admin/policy_set_templates.new_policy_set_template.tsx",
      "parent": "/__auth/admin/policy_set_templates",
      "children": [
        "/__auth/admin/policy_set_templates/new_policy_set_template/add_policies",
        "/__auth/admin/policy_set_templates/new_policy_set_template/define_policy_set_template",
        "/__auth/admin/policy_set_templates/new_policy_set_template/review_and_submit"
      ]
    },
    "/__auth/member/new_policy_set/add_policies": {
      "filePath": "__auth/member/new_policy_set/add_policies.tsx",
      "parent": "/__auth/member/new_policy_set"
    },
    "/__auth/member/new_policy_set/define_policy_set": {
      "filePath": "__auth/member/new_policy_set/define_policy_set.tsx",
      "parent": "/__auth/member/new_policy_set"
    },
    "/__auth/member/new_policy_set/prefill_template": {
      "filePath": "__auth/member/new_policy_set/prefill_template.tsx",
      "parent": "/__auth/member/new_policy_set"
    },
    "/__auth/member/new_policy_set/review_and_submit": {
      "filePath": "__auth/member/new_policy_set/review_and_submit.tsx",
      "parent": "/__auth/member/new_policy_set"
    },
    "/__auth/admin/policy_set/$policySetId/add_policy": {
      "filePath": "__auth/admin/policy_set.$policySetId.add_policy.tsx",
      "parent": "/__auth/admin/policy_set"
    },
    "/__auth/admin/policy_set_templates/detail/$policySetTemplateId": {
      "filePath": "__auth/admin/policy_set_templates.detail.$policySetTemplateId.tsx",
      "parent": "/__auth/admin/policy_set_templates"
    },
    "/__auth/admin/policy_set_templates/new_policy_set_template/add_policies": {
      "filePath": "__auth/admin/policy_set_templates.new_policy_set_template/add_policies.tsx",
      "parent": "/__auth/admin/policy_set_templates/new_policy_set_template"
    },
    "/__auth/admin/policy_set_templates/new_policy_set_template/define_policy_set_template": {
      "filePath": "__auth/admin/policy_set_templates.new_policy_set_template/define_policy_set_template.tsx",
      "parent": "/__auth/admin/policy_set_templates/new_policy_set_template"
    },
    "/__auth/admin/policy_set_templates/new_policy_set_template/review_and_submit": {
      "filePath": "__auth/admin/policy_set_templates.new_policy_set_template/review_and_submit.tsx",
      "parent": "/__auth/admin/policy_set_templates/new_policy_set_template"
    },
    "/__auth/member/policy_set/$policySetId/add_policy": {
      "filePath": "__auth/member/policy_set.$policySetId.add_policy.tsx",
      "parent": "/__auth/member"
    },
    "/__auth/admin/policy_set/$policySetId/": {
      "filePath": "__auth/admin/policy_set.$policySetId.index.tsx",
      "parent": "/__auth/admin/policy_set"
    },
    "/__auth/member/policy_set/$policySetId/": {
      "filePath": "__auth/member/policy_set.$policySetId.index.tsx",
      "parent": "/__auth/member"
    },
    "/__auth/admin/policy_set/$policySetId/edit_policy/$policyId": {
      "filePath": "__auth/admin/policy_set.$policySetId.edit_policy.$policyId.tsx",
      "parent": "/__auth/admin/policy_set"
    },
    "/__auth/member/policy_set/$policySetId/edit_policy/$policyId": {
      "filePath": "__auth/member/policy_set.$policySetId.edit_policy.$policyId.tsx",
      "parent": "/__auth/member"
    }
  }
}
ROUTE_MANIFEST_END */
