/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as authImport } from "./routes/__auth";
import { Route as authIndexImport } from "./routes/__auth/index";
import { Route as authNewpolicysetImport } from "./routes/__auth/new_policy_set";
import { Route as authPolicysetPolicySetIdIndexImport } from "./routes/__auth/policy_set.$policySetId.index";
import { Route as authPolicysetPolicySetIdAddpolicyStep3Import } from "./routes/__auth/policy_set.$policySetId.add_policy/step3";
import { Route as authPolicysetPolicySetIdAddpolicyStep2Import } from "./routes/__auth/policy_set.$policySetId.add_policy/step2";
import { Route as authPolicysetPolicySetIdAddpolicyStep1Import } from "./routes/__auth/policy_set.$policySetId.add_policy/step1";

// Create/Update Routes

const authRoute = authImport.update({
  id: "/__auth",
  getParentRoute: () => rootRoute,
} as any);

const authIndexRoute = authIndexImport.update({
  path: "/",
  getParentRoute: () => authRoute,
} as any);

const authNewpolicysetRoute = authNewpolicysetImport.update({
  path: "/new_policy_set",
  getParentRoute: () => authRoute,
} as any);

const authPolicysetPolicySetIdIndexRoute =
  authPolicysetPolicySetIdIndexImport.update({
    path: "/policy_set/$policySetId/",
    getParentRoute: () => authRoute,
  } as any);

const authPolicysetPolicySetIdAddpolicyStep3Route =
  authPolicysetPolicySetIdAddpolicyStep3Import.update({
    path: "/policy_set/$policySetId/add_policy/step3",
    getParentRoute: () => authRoute,
  } as any);

const authPolicysetPolicySetIdAddpolicyStep2Route =
  authPolicysetPolicySetIdAddpolicyStep2Import.update({
    path: "/policy_set/$policySetId/add_policy/step2",
    getParentRoute: () => authRoute,
  } as any);

const authPolicysetPolicySetIdAddpolicyStep1Route =
  authPolicysetPolicySetIdAddpolicyStep1Import.update({
    path: "/policy_set/$policySetId/add_policy/step1",
    getParentRoute: () => authRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/__auth": {
      id: "/__auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof authImport;
      parentRoute: typeof rootRoute;
    };
    "/__auth/new_policy_set": {
      id: "/__auth/new_policy_set";
      path: "/new_policy_set";
      fullPath: "/new_policy_set";
      preLoaderRoute: typeof authNewpolicysetImport;
      parentRoute: typeof authImport;
    };
    "/__auth/": {
      id: "/__auth/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof authIndexImport;
      parentRoute: typeof authImport;
    };
    "/__auth/policy_set/$policySetId/": {
      id: "/__auth/policy_set/$policySetId/";
      path: "/policy_set/$policySetId";
      fullPath: "/policy_set/$policySetId";
      preLoaderRoute: typeof authPolicysetPolicySetIdIndexImport;
      parentRoute: typeof authImport;
    };
    "/__auth/policy_set/$policySetId/add_policy/step1": {
      id: "/__auth/policy_set/$policySetId/add_policy/step1";
      path: "/policy_set/$policySetId/add_policy/step1";
      fullPath: "/policy_set/$policySetId/add_policy/step1";
      preLoaderRoute: typeof authPolicysetPolicySetIdAddpolicyStep1Import;
      parentRoute: typeof authImport;
    };
    "/__auth/policy_set/$policySetId/add_policy/step2": {
      id: "/__auth/policy_set/$policySetId/add_policy/step2";
      path: "/policy_set/$policySetId/add_policy/step2";
      fullPath: "/policy_set/$policySetId/add_policy/step2";
      preLoaderRoute: typeof authPolicysetPolicySetIdAddpolicyStep2Import;
      parentRoute: typeof authImport;
    };
    "/__auth/policy_set/$policySetId/add_policy/step3": {
      id: "/__auth/policy_set/$policySetId/add_policy/step3";
      path: "/policy_set/$policySetId/add_policy/step3";
      fullPath: "/policy_set/$policySetId/add_policy/step3";
      preLoaderRoute: typeof authPolicysetPolicySetIdAddpolicyStep3Import;
      parentRoute: typeof authImport;
    };
  }
}

// Create and export the route tree

interface authRouteChildren {
  authNewpolicysetRoute: typeof authNewpolicysetRoute;
  authIndexRoute: typeof authIndexRoute;
  authPolicysetPolicySetIdIndexRoute: typeof authPolicysetPolicySetIdIndexRoute;
  authPolicysetPolicySetIdAddpolicyStep1Route: typeof authPolicysetPolicySetIdAddpolicyStep1Route;
  authPolicysetPolicySetIdAddpolicyStep2Route: typeof authPolicysetPolicySetIdAddpolicyStep2Route;
  authPolicysetPolicySetIdAddpolicyStep3Route: typeof authPolicysetPolicySetIdAddpolicyStep3Route;
}

const authRouteChildren: authRouteChildren = {
  authNewpolicysetRoute: authNewpolicysetRoute,
  authIndexRoute: authIndexRoute,
  authPolicysetPolicySetIdIndexRoute: authPolicysetPolicySetIdIndexRoute,
  authPolicysetPolicySetIdAddpolicyStep1Route:
    authPolicysetPolicySetIdAddpolicyStep1Route,
  authPolicysetPolicySetIdAddpolicyStep2Route:
    authPolicysetPolicySetIdAddpolicyStep2Route,
  authPolicysetPolicySetIdAddpolicyStep3Route:
    authPolicysetPolicySetIdAddpolicyStep3Route,
};

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren);

export interface FileRoutesByFullPath {
  "": typeof authRouteWithChildren;
  "/new_policy_set": typeof authNewpolicysetRoute;
  "/": typeof authIndexRoute;
  "/policy_set/$policySetId": typeof authPolicysetPolicySetIdIndexRoute;
  "/policy_set/$policySetId/add_policy/step1": typeof authPolicysetPolicySetIdAddpolicyStep1Route;
  "/policy_set/$policySetId/add_policy/step2": typeof authPolicysetPolicySetIdAddpolicyStep2Route;
  "/policy_set/$policySetId/add_policy/step3": typeof authPolicysetPolicySetIdAddpolicyStep3Route;
}

export interface FileRoutesByTo {
  "/new_policy_set": typeof authNewpolicysetRoute;
  "/": typeof authIndexRoute;
  "/policy_set/$policySetId": typeof authPolicysetPolicySetIdIndexRoute;
  "/policy_set/$policySetId/add_policy/step1": typeof authPolicysetPolicySetIdAddpolicyStep1Route;
  "/policy_set/$policySetId/add_policy/step2": typeof authPolicysetPolicySetIdAddpolicyStep2Route;
  "/policy_set/$policySetId/add_policy/step3": typeof authPolicysetPolicySetIdAddpolicyStep3Route;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/__auth": typeof authRouteWithChildren;
  "/__auth/new_policy_set": typeof authNewpolicysetRoute;
  "/__auth/": typeof authIndexRoute;
  "/__auth/policy_set/$policySetId/": typeof authPolicysetPolicySetIdIndexRoute;
  "/__auth/policy_set/$policySetId/add_policy/step1": typeof authPolicysetPolicySetIdAddpolicyStep1Route;
  "/__auth/policy_set/$policySetId/add_policy/step2": typeof authPolicysetPolicySetIdAddpolicyStep2Route;
  "/__auth/policy_set/$policySetId/add_policy/step3": typeof authPolicysetPolicySetIdAddpolicyStep3Route;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | ""
    | "/new_policy_set"
    | "/"
    | "/policy_set/$policySetId"
    | "/policy_set/$policySetId/add_policy/step1"
    | "/policy_set/$policySetId/add_policy/step2"
    | "/policy_set/$policySetId/add_policy/step3";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/new_policy_set"
    | "/"
    | "/policy_set/$policySetId"
    | "/policy_set/$policySetId/add_policy/step1"
    | "/policy_set/$policySetId/add_policy/step2"
    | "/policy_set/$policySetId/add_policy/step3";
  id:
    | "__root__"
    | "/__auth"
    | "/__auth/new_policy_set"
    | "/__auth/"
    | "/__auth/policy_set/$policySetId/"
    | "/__auth/policy_set/$policySetId/add_policy/step1"
    | "/__auth/policy_set/$policySetId/add_policy/step2"
    | "/__auth/policy_set/$policySetId/add_policy/step3";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  authRoute: typeof authRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  authRoute: authRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/__auth"
      ]
    },
    "/__auth": {
      "filePath": "__auth.tsx",
      "children": [
        "/__auth/new_policy_set",
        "/__auth/",
        "/__auth/policy_set/$policySetId/",
        "/__auth/policy_set/$policySetId/add_policy/step1",
        "/__auth/policy_set/$policySetId/add_policy/step2",
        "/__auth/policy_set/$policySetId/add_policy/step3"
      ]
    },
    "/__auth/new_policy_set": {
      "filePath": "__auth/new_policy_set.tsx",
      "parent": "/__auth"
    },
    "/__auth/": {
      "filePath": "__auth/index.tsx",
      "parent": "/__auth"
    },
    "/__auth/policy_set/$policySetId/": {
      "filePath": "__auth/policy_set.$policySetId.index.tsx",
      "parent": "/__auth"
    },
    "/__auth/policy_set/$policySetId/add_policy/step1": {
      "filePath": "__auth/policy_set.$policySetId.add_policy/step1.tsx",
      "parent": "/__auth"
    },
    "/__auth/policy_set/$policySetId/add_policy/step2": {
      "filePath": "__auth/policy_set.$policySetId.add_policy/step2.tsx",
      "parent": "/__auth"
    },
    "/__auth/policy_set/$policySetId/add_policy/step3": {
      "filePath": "__auth/policy_set.$policySetId.add_policy/step3.tsx",
      "parent": "/__auth"
    }
  }
}
ROUTE_MANIFEST_END */
